"use client";

import {FormEvent,useEffect,useState} from "react";
import AppShell from "../../components/AppShell";
import AiReport from "../../components/AiReport";
import TrainingZoneStatus from "../../components/TrainingZoneStatus";
import {api} from "../../lib/api";
import {bi,useI18n} from "../../lib/i18n";

type AnyObj=Record<string,any>;
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const GOALS=[
  ["muscle_gain","Muskelaufbau","Muscle gain"],["cardio_endurance","Cardio / Ausdauer","Cardio / endurance"],["hybrid","Hybrid · Kraft + Ausdauer","Hybrid · strength + endurance"],["cycling_endurance","Radsport-Ausdauer","Cycling endurance"],["running_5k","Laufen · 5 km","Running · 5K"],["running_10k","Laufen · 10 km","Running · 10K"],["half_marathon","Halbmarathon","Half marathon"],["marathon","Marathon","Marathon"],["strength","Kraft","Strength"],["general_fitness","Allgemeine Fitness","General fitness"],["mobility","Mobilität","Mobility"],["custom","Eigenes Ziel","Custom goal"],
];

export default function Training(){
  const{lang}=useI18n();const de=lang!=="en";
  const[caps,setCaps]=useState<AnyObj|null>(null),[history,setHistory]=useState<AnyObj[]>([]),[result,setResult]=useState<AnyObj|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[status,setStatus]=useState("");
  const[goalType,setGoalType]=useState("hybrid"),[goalText,setGoalText]=useState(""),[experience,setExperience]=useState("intermediate"),[weeks,setWeeks]=useState(8),[days,setDays]=useState(4),[minutes,setMinutes]=useState(60),[equipment,setEquipment]=useState(""),[constraints,setConstraints]=useState("");
  const[model,setModel]=useState(""),[tokens,setTokens]=useState(4500),[ctx,setCtx]=useState(8192),[prompt,setPrompt]=useState("");
  const jobKey="pengucoach_training_plan_job";
  useEffect(()=>{void Promise.all([api<AnyObj>(`/coach/capabilities?locale=${lang}`),api<AnyObj[]>("/coach/training-plans")]).then(([c,h])=>{setCaps(c);setHistory(h);const t=c.tasks?.training_plan??{};setModel(t.default_model_id??"");setTokens(t.max_output_tokens??4500);setCtx(t.context_window_tokens??8192);setPrompt(t.default_prompt??"");if(h.length)setResult(h[0])}).catch(e=>setError(String(e)));const j=localStorage.getItem(jobKey);if(j){setBusy(true);void poll(j)}},[lang]);
  const task=caps?.tasks?.training_plan??{};const models=caps?.eligible_models??[];const selected=models.find((x:AnyObj)=>x.id===model);const meta=result?.metadata??result??{};const usage=result?.usage??meta.usage??{};const truncated=Boolean(result?.truncated??meta.truncated);
  async function poll(jobId:string){setStatus(de?"Trainingsplan wird im Hintergrund erstellt…":"Training plan is being generated in the background…");for(let i=0;i<900;i++){try{const j=await api<AnyObj>(`/jobs/${jobId}`);if(j.ready){localStorage.removeItem(jobKey);setBusy(false);if(j.successful&&j.result){setResult(j.result);setHistory(v=>[j.result,...v].slice(0,10));setStatus(de?"Plan fertig":"Plan ready");return}setError(j.error||"AI job failed");return}setStatus(j.progress?.message||status)}catch{}await sleep(1500)}setBusy(false)}
  async function generate(e:FormEvent){e.preventDefault();if(busy||!model)return;setBusy(true);setError("");setStatus(de?"Plan wird vorbereitet…":"Preparing plan…");try{const r=await api<AnyObj>("/coach/training-plan/jobs",{method:"POST",body:JSON.stringify({goal_type:goalType,goal_text:goalText,experience,weeks,days_per_week:days,session_minutes:minutes,equipment,constraints,prompt:prompt||null,model_id:model,max_tokens:tokens,context_window_tokens:ctx,locale:lang})});localStorage.setItem(jobKey,r.task_id);void poll(r.task_id)}catch(e){setBusy(false);setError(e instanceof Error?e.message:String(e))}}
  return <AppShell>
    <div className="coach-modern-head"><div><span className="eyebrow">AI TRAINING PLANNER</span><h1>{bi(lang,"Trainingsplanung","Training planning")}</h1><p className="muted">{bi(lang,"Ziel definieren, verfügbare Zeit festlegen und einen periodisierten Plan auf Basis deiner letzten 7/28 Tage erstellen.","Define your goal, available time and create a periodized plan using your last 7/28 days.")}</p></div><div className="coach-model-chip"><span className={`ai-local-dot ${selected?.local?"local":"cloud"}`}/><div><small>{bi(lang,"Aktives Modell","Active model")}</small><strong>{selected?.display_name??task.default_model??"—"}</strong><span>{selected?.provider??task.default_provider??""}</span></div></div></div>

    <form className="card training-modern" onSubmit={generate}>
      <div className="training-step"><span>01</span><div><h2>{bi(lang,"Ziel & Rahmen","Goal & framework")}</h2><p className="muted">{bi(lang,"Was willst du erreichen und wie viel Zeit steht realistisch zur Verfügung?","What do you want to achieve and how much time is realistically available?")}</p></div></div>
      <div className="training-form-grid"><label>{bi(lang,"Ziel","Goal")}<select value={goalType} onChange={e=>setGoalType(e.target.value)}>{GOALS.map(x=><option key={x[0]} value={x[0]}>{de?x[1]:x[2]}</option>)}</select></label><label>{bi(lang,"Erfahrung","Experience")}<select value={experience} onChange={e=>setExperience(e.target.value)}><option value="beginner">{bi(lang,"Einsteiger","Beginner")}</option><option value="intermediate">{bi(lang,"Fortgeschritten","Intermediate")}</option><option value="advanced">{bi(lang,"Erfahren","Advanced")}</option></select></label><label>{bi(lang,"Wochen","Weeks")}<input type="number" min={1} max={24} value={weeks} onChange={e=>setWeeks(Number(e.target.value))}/></label><label>{bi(lang,"Trainingstage / Woche","Training days / week")}<input type="number" min={1} max={7} value={days} onChange={e=>setDays(Number(e.target.value))}/></label><label>{bi(lang,"Typische Session","Typical session")}<div className="ai-number-control"><input type="number" min={15} max={240} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/><span>min</span></div></label></div>
      <label>{bi(lang,"Dein konkretes Ziel","Your specific goal")}<textarea value={goalText} onChange={e=>setGoalText(e.target.value)} placeholder={bi(lang,"z. B. 10 km unter 50 Minuten, mehr Muskelmasse und trotzdem zweimal Rad pro Woche …","e.g. run 10K under 50 minutes, gain muscle while cycling twice a week …")}/></label>
      <div className="grid2"><label>{bi(lang,"Equipment / Möglichkeiten","Equipment / facilities")}<textarea value={equipment} onChange={e=>setEquipment(e.target.value)} placeholder={bi(lang,"Fitnessstudio, Hantelbank, Rennrad, Laufband …","Gym, bench, road bike, treadmill …")}/></label><label>{bi(lang,"Einschränkungen / feste Tage","Constraints / fixed days")}<textarea value={constraints} onChange={e=>setConstraints(e.target.value)} placeholder={bi(lang,"Mittwoch frei, werktags max. 90 Minuten …","Wednesday off, max 90 minutes on weekdays …")}/></label></div>

      <div className="training-step"><span>02</span><div><h2>{bi(lang,"AI Budget","AI budget")}</h2><p className="muted">{bi(lang,"Kontext und Antwortlänge bewusst steuern. Bei Ollama wird num_ctx direkt gesetzt.","Control context and response length explicitly. For Ollama, num_ctx is set directly.")}</p></div></div>
      <div className="ai-analysis-settings"><label>{bi(lang,"Modell","Model")}<select value={model} onChange={e=>setModel(e.target.value)}>{models.map((x:AnyObj)=><option key={x.id} value={x.id}>{x.display_name} · {x.provider} · {x.local?"LOCAL":"CLOUD"}</option>)}</select></label><label>{bi(lang,"Kontextfenster","Context window")}<div className="ai-number-control"><input type="number" min={2048} max={task.context_window_tokens??262144} step={1024} value={ctx} onChange={e=>setCtx(Math.min(task.context_window_tokens??262144,Number(e.target.value)))}/><span>tokens</span></div></label><label>{bi(lang,"Max. Antwort","Max response")}<div className="ai-number-control"><input type="number" min={128} max={task.max_output_tokens??8192} step={1} value={tokens} onChange={e=>setTokens(Math.min(task.max_output_tokens??8192,Number(e.target.value)))}/><span>tokens</span></div></label><div className="card subtle ai-budget"><span>{bi(lang,"Trainingskontext","Training context")}</span><strong>7d + 28d Garmin/FIT</strong><small>ctx {ctx.toLocaleString()} · out {tokens.toLocaleString()}</small></div></div>
      <TrainingZoneStatus/>
      <details className="ai-prompt-details"><summary>{bi(lang,"Planungs-Prompt anzeigen / anpassen","Show / edit planning prompt")}</summary><textarea className="prompt-editor modern" value={prompt} onChange={e=>setPrompt(e.target.value)}/></details>
      <div className="between"><div>{status&&<span className={`ai-job-status ${busy?"running":""}`}>{busy&&<i/>}{status}</span>}{error&&<div className="status-bad">{error}</div>}</div><button disabled={busy||!model}>{busy?bi(lang,"Plan läuft im Hintergrund…","Plan running in background…"):bi(lang,"Trainingsplan erstellen","Create training plan")}</button></div>
    </form>

    {result&&<section className="card ai-result-modern"><div className="ai-result-head"><div><span className="eyebrow">AI TRAINING PLAN</span><h2>{bi(lang,"Aktueller Plan","Current plan")}</h2></div><div className="ai-run-meta-modern"><strong>{result.model??result.model_name}</strong><div><span>{result.provider??result.provider_name}</span><span>ctx {result.context_window_tokens??meta.context_window_tokens??"—"}</span><span>{result.max_output_tokens??"—"} out</span></div></div></div>{truncated&&<div className="ai-truncated-warning">⚠ {bi(lang,"Antwortlimit erreicht – der Plan wurde möglicherweise abgeschnitten. Erhöhe das Antwortbudget und erstelle ihn neu.","Response limit reached — the plan may be truncated. Increase the response budget and regenerate it.")}</div>}<div className="ai-content modern"><AiReport content={result.content}/></div><div className="ai-result-stats"><span>{usage.input_tokens??"?"} in</span><span>{usage.output_tokens??"?"} out</span><span>{meta.stop_reason??result.stop_reason??"stop"}</span></div></section>}

    {history.length>1&&<section className="card"><h2>{bi(lang,"Frühere Pläne","Previous plans")}</h2><div className="plan-history">{history.slice(0,8).map((x:AnyObj)=><button className="history-row" type="button" key={x.id??x.run_id} onClick={()=>setResult(x)}><span><strong>{x.metadata?.goal?.goal_type??bi(lang,"Trainingsplan","Training plan")}</strong><small>{x.created_at?new Date(x.created_at).toLocaleString(de?"de-DE":"en-GB"):""}</small></span><span>{x.model??x.model_name}</span></button>)}</div></section>}
  </AppShell>
}
