"use client";

import {FormEvent,useEffect,useState} from "react";
import AppShell from "../../../components/AppShell";
import {api} from "../../../lib/api";
import {bi,useI18n} from "../../../lib/i18n";

type AnyObj=Record<string,any>;
type Settings={sync_days:number;sync_sleep:boolean;sync_daily_health:boolean;sync_activities:boolean};
type Status={connected:boolean;status:string;read_only:boolean;base_url?:string;capabilities?:Record<string,boolean>;counts?:Record<string,number>;last_validated_at?:string;last_successful_sync_at?:string;last_error_code?:string;last_sync_summary?:AnyObj;settings:Settings};
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
const JOB_KEY="pengucoach_sparkyfitness_sync_job";

function capabilityLabel(key:string,de:boolean){
  const labels:Record<string,[string,string]>={identity:["API-Key","API key"],activities:["Training & Aktivitäten","Training & activities"],sleep:["Schlaf","Sleep"],checkins:["Tageswerte & Körperdaten","Daily & body metrics"],custom_metrics:["HRV & benutzerdefinierte Metriken","HRV & custom metrics"],dashboard:["Dashboard-Tageswerte","Dashboard daily metrics"]};
  const value=labels[key]??[key,key];return de?value[0]:value[1];
}
function dt(value?:string,lang="de"){if(!value)return "—";const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString(lang==="de"?"de-DE":"en-GB")}

export default function SparkyFitnessPage(){
  const{lang}=useI18n();const de=lang==="de";
  const[status,setStatus]=useState<Status|null>(null),[baseUrl,setBaseUrl]=useState(""),[apiKey,setApiKey]=useState(""),[busy,setBusy]=useState(false),[syncing,setSyncing]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
  const refresh=()=>api<Status>("/sparkyfitness/status").then(v=>{setStatus(v);if(v.base_url)setBaseUrl(v.base_url.replace(/\/api\/?$/,""))});
  useEffect(()=>{void refresh();const job=localStorage.getItem(JOB_KEY);if(job){setSyncing(true);void poll(job)}// eslint-disable-next-line react-hooks/exhaustive-deps
  },[]);

  async function connect(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError("");setMessage("");try{const settings=status?.settings??{sync_days:30,sync_sleep:true,sync_daily_health:true,sync_activities:true};await api("/sparkyfitness/connect",{method:"POST",body:JSON.stringify({base_url:baseUrl,api_key:apiKey,...settings})});setApiKey("");setMessage(bi(lang,"SparkyFitness verbunden. Die Verbindung ist read-only.","SparkyFitness connected. The connection is read-only."));await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  async function test(){setBusy(true);setError("");try{await api("/sparkyfitness/test",{method:"POST"});setMessage(bi(lang,"Verbindung und Berechtigungen erfolgreich geprüft.","Connection and permissions verified successfully."));await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  async function save(){if(!status)return;setBusy(true);setError("");try{await api("/sparkyfitness/settings",{method:"PUT",body:JSON.stringify(status.settings)});setMessage(bi(lang,"Einstellungen gespeichert.","Settings saved."));await refresh()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  async function disconnect(){if(!confirm(bi(lang,"SparkyFitness trennen? Bereits importierte lokale Daten bleiben erhalten.","Disconnect SparkyFitness? Already imported local data will be preserved.")))return;setBusy(true);try{await api("/sparkyfitness/disconnect",{method:"POST"});setMessage(bi(lang,"SparkyFitness getrennt. Lokale Daten wurden beibehalten.","SparkyFitness disconnected. Local data was preserved."));setBaseUrl("");await refresh()}finally{setBusy(false)}}
  function patchSettings(p:Partial<Settings>){if(!status)return;setStatus({...status,settings:{...status.settings,...p}})}
  async function syncNow(){if(syncing)return;setSyncing(true);setError("");setMessage(bi(lang,"SparkyFitness-Sync wird gestartet…","Starting SparkyFitness sync…"));try{const r=await api<AnyObj>("/sparkyfitness/sync/now",{method:"POST"});localStorage.setItem(JOB_KEY,r.task_id);await poll(r.task_id)}catch(e){setSyncing(false);setError(e instanceof Error?e.message:String(e))}}
  async function poll(taskId:string){setSyncing(true);for(let i=0;i<2400;i++){try{const j=await api<AnyObj>(`/jobs/${taskId}`);if(j.ready){localStorage.removeItem(JOB_KEY);setSyncing(false);if(j.successful){const r=j.result??{};setMessage(bi(lang,`Sync abgeschlossen · ${r.sleep_entries??0} Schlaf · ${r.checkins??0} Tageswerte · ${r.activities?.sessions??0} Trainings-Sessions.`,`Sync completed · ${r.sleep_entries??0} sleep · ${r.checkins??0} daily metrics · ${r.activities?.sessions??0} training sessions.`));await refresh()}else setError(j.error||"SparkyFitness sync failed");return}const phase=String(j.progress?.phase??"");const labels:Record<string,[string,string]>={daily_health:["Tageswerte werden gelesen…","Reading daily metrics…"],sleep:["Schlafdaten werden gelesen…","Reading sleep data…"],activities:[`Trainingshistorie · Seite ${j.progress?.pages??j.progress?.page??"?"} · ${j.progress?.sessions??0} Sessions`,`Training history · page ${j.progress?.pages??j.progress?.page??"?"} · ${j.progress?.sessions??0} sessions`]};if(labels[phase])setMessage(de?labels[phase][0]:labels[phase][1])}catch{}await sleep(1250)}setSyncing(false);setError(bi(lang,"Der SparkyFitness-Sync läuft ungewöhnlich lange. Worker-Status prüfen.","The SparkyFitness sync is taking unusually long. Check worker status."))}

  const caps=status?.capabilities??{};const counts=status?.counts??{};
  return <AppShell><div><span className="eyebrow">CONNECTION</span><h1>SparkyFitness</h1><p className="muted">{bi(lang,"Apple Health und weitere in SparkyFitness zusammengeführte Gesundheits- und Trainingsdaten zusätzlich zu Garmin lesen.","Read Apple Health and other health/training data consolidated in SparkyFitness in addition to Garmin.")}</p></div>
    {!status?.connected?<section className="card stack"><div className="connection-hero"><div className="connection-logo sparky">S</div><div><h2>{bi(lang,"SparkyFitness verbinden","Connect SparkyFitness")}</h2><p>{bi(lang,"PenguCoach verwendet ausschließlich lesende API-Aufrufe. URL und API-Key bleiben installationsspezifisch.","PenguCoach uses read-only API calls only. URL and API key remain installation-specific.")}</p></div></div><form className="stack" onSubmit={connect}><label>{bi(lang,"SparkyFitness URL","SparkyFitness URL")}<input required value={baseUrl} onChange={e=>setBaseUrl(e.target.value)} placeholder="https://fitness.example.com"/><small>{bi(lang,"Die normale Frontend-URL genügt; PenguCoach ergänzt /api automatisch.","The normal frontend URL is enough; PenguCoach adds /api automatically.")}</small></label><label>API Key<input required type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="off" placeholder="••••••••••••"/><small>{bi(lang,"In SparkyFitness unter API Key Management erzeugen. Der Key wird verschlüsselt gespeichert.","Create it in SparkyFitness API Key Management. The key is stored encrypted.")}</small></label><button disabled={busy}>{busy?bi(lang,"Prüfe Verbindung…","Checking connection…"):bi(lang,"Verbinden & Berechtigungen prüfen","Connect & check permissions")}</button></form></section>:
    <><section className="card stack"><div className="connection-status-head"><div className="connection-logo sparky">S</div><div><span className="status-ok">● {bi(lang,"Verbunden","Connected")}</span><h2>{status.base_url?.replace(/\/api\/?$/,'')}</h2><small>{bi(lang,"Read-only · API-Key verschlüsselt gespeichert","Read-only · API key stored encrypted")}</small></div></div><div className="connection-kpis"><div><strong>{Object.values(counts).reduce((a,b)=>a+Number(b||0),0).toLocaleString()}</strong><span>{bi(lang,"Rohdatensätze","raw records")}</span></div><div><strong>{Number(counts.exercise_session??0).toLocaleString()}</strong><span>{bi(lang,"Trainings-Sessions","training sessions")}</span></div><div><strong>{Number(counts.sleep??0).toLocaleString()}</strong><span>{bi(lang,"Schlaf-Einträge","sleep entries")}</span></div></div><div className="capability-grid">{Object.entries(caps).filter(([k])=>k!=="identity").map(([key,value])=><div className={value?"capability ok":"capability off"} key={key}><span>{value?"✓":"—"}</span><div><strong>{capabilityLabel(key,de)}</strong><small>{value?bi(lang,"verfügbar","available"):bi(lang,"nicht freigegeben / nicht verfügbar","not permitted / unavailable")}</small></div></div>)}</div><div className="connection-meta"><span>{bi(lang,"Zuletzt geprüft","Last checked")}: <strong>{dt(status.last_validated_at,lang)}</strong></span><span>{bi(lang,"Letzter Sync","Last sync")}: <strong>{dt(status.last_successful_sync_at,lang)}</strong></span></div><div className="form-actions"><button className="ghost" disabled={busy||syncing} onClick={test}>{bi(lang,"Verbindung testen","Test connection")}</button><button className="ghost danger" disabled={busy||syncing} onClick={disconnect}>{bi(lang,"Trennen","Disconnect")}</button></div></section>
    <section className="card stack"><div><span className="eyebrow">SYNC</span><h2>{bi(lang,"Datenübernahme","Data import")}</h2><p className="muted">{bi(lang,"SparkyFitness ergänzt fehlende allgemeine Gesundheitswerte. Vorhandene Garmin-Werte werden nicht überschrieben. Trainings-Sessions werden als zusätzliche Quelle für den AI Coach gespeichert.","SparkyFitness fills missing general health metrics. Existing Garmin values are not overwritten. Training sessions are stored as an additional source for the AI Coach.")}</p></div><div className="grid2"><label>{bi(lang,"Zeitraum je Sync","Period per sync")}<select value={status.settings.sync_days} onChange={e=>patchSettings({sync_days:Number(e.target.value)})}><option value={7}>7 {bi(lang,"Tage","days")}</option><option value={14}>14 {bi(lang,"Tage","days")}</option><option value={30}>30 {bi(lang,"Tage","days")}</option><option value={90}>90 {bi(lang,"Tage","days")}</option><option value={180}>180 {bi(lang,"Tage","days")}</option><option value={366}>366 {bi(lang,"Tage","days")}</option></select></label></div><label className="switch-row"><input type="checkbox" checked={status.settings.sync_activities} disabled={!caps.activities} onChange={e=>patchSettings({sync_activities:e.target.checked})}/><span/><div><strong>{bi(lang,"Training & Aktivitäten","Training & activities")}</strong><small>{bi(lang,"Paginierte SparkyFitness-Trainingshistorie als zusätzliche AI-Quelle","Paginated SparkyFitness training history as an additional AI source")}</small></div></label><label className="switch-row"><input type="checkbox" checked={status.settings.sync_sleep} disabled={!caps.sleep} onChange={e=>patchSettings({sync_sleep:e.target.checked})}/><span/><div><strong>{bi(lang,"Schlaf","Sleep")}</strong><small>{bi(lang,"Dauer, Score und – soweit vorhanden – Schlafphasen","Duration, score and sleep stages where available")}</small></div></label><label className="switch-row"><input type="checkbox" checked={status.settings.sync_daily_health} disabled={!caps.checkins} onChange={e=>patchSettings({sync_daily_health:e.target.checked})}/><span/><div><strong>{bi(lang,"Tageswerte, HRV & Körperdaten","Daily metrics, HRV & body data")}</strong><small>{bi(lang,"Schritte, Gewicht, Körperfett sowie HRV/Ruhepuls aus verfügbaren Custom Metrics","Steps, weight, body fat and HRV/resting HR from available custom metrics")}</small></div></label><div className="form-actions"><button disabled={busy||syncing} onClick={save}>{bi(lang,"Einstellungen speichern","Save settings")}</button><button disabled={busy||syncing} onClick={syncNow}>{syncing?bi(lang,"Synchronisierung läuft…","Syncing…"):bi(lang,"Jetzt synchronisieren","Sync now")}</button></div></section></>}
    {message&&<div className="ai-toast">{message}</div>}{error&&<div className="status-bad">{error}</div>}
  </AppShell>;
}
