"""Initial PenguCoach schema.

Revision ID: 0001_initial
Revises: None
"""
from alembic import op

from pengucoach.db.base import Base
import pengucoach.db.models  # noqa: F401

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Baseline migration: create the complete v0.1 schema from reviewed metadata.
    # Future revisions use explicit ALTER/CREATE operations generated by Alembic.
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
