"use client";
import {FormEvent,useEffect,useState} from "react";
import AppShell from "../../../components/AppShell";
import {api} from "../../../lib/api";
import {bi,useI18n} from "../../../lib/i18n";

type Status={connected:boolean;status:string;display_name?:string;last_successful_sync_at?:string;next_sync_at?:string;cooldown_until?:string;last_error_code?:string;settings?:{enabled:boolean;interval_minutes:number;fit_download_enabled:boolean;fit_analysis_enabled:boolean;historical_days:number}};

export default function GarminSettings(){
  const{lang}=useI18n();
  const[status,setStatus]=useState<Status|null>(null),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[challenge,setChallenge]=useState(""),[code,setCode]=useState(""),[msg,setMsg]=useState(""),[syncing,setSyncing]=useState(false),[historyOpen,setHistoryOpen]=useState(false);
  const refresh=()=>api<Status>("/garmin/status").then(setStatus);
  useEffect(()=>{void refresh()},[]);
  async function connect(e:FormEvent){e.preventDefault();setMsg("");try{const r=await api<any>("/garmin/auth/start",{method:"POST",body:JSON.stringify({email,password})});setPassword("");if(r.status==="mfa_required")setChallenge(r.challenge_id);else{setMsg(bi(lang,"Garmin verbunden","Garmin connected"));refresh()}}catch(e){setMsg(e instanceof Error?e.message:"Error")}}
  async function mfa(e:FormEvent){e.preventDefault();try{await api("/garmin/auth/mfa",{method:"POST",body:JSON.stringify({challenge_id:challenge,code})});setChallenge("");setCode("");setMsg(bi(lang,"Garmin verbunden","Garmin connected"));refresh()}catch(e){setMsg(e instanceof Error?e.message:"Error")}}
  async function sync(){setSyncing(true);try{const r=await api<any>("/garmin/sync/now",{method:"POST"});setMsg(`${bi(lang,"Synchronisierung gestartet","Synchronization started")} · ${r.task_id}`);setTimeout(()=>void refresh(),2500)}finally{setSyncing(false)}}
  async function saveSettings(){if(!status?.settings)return;await api("/garmin/sync/settings",{method:"PUT",body:JSON.stringify(status.settings)});setMsg(bi(lang,"Einstellungen gespeichert","Settings saved"));refresh()}
  async function startImport(){const days=status?.settings?.historical_days??365;const r=await api<any>("/garmin/import",{method:"POST",body:JSON.stringify({days})});setMsg(`${bi(lang,"Historienimport gestartet","History import started")} · ${r.task_id}`)}
  async function disconnect(){if(!confirm(bi(lang,"Garmin trennen? Lokale Daten bleiben erhalten.","Disconnect Garmin? Local data is preserved.")))return;await api("/garmin/disconnect",{method:"POST"});refresh()}
  return <AppShell title="Garmin">
    <div className="garmin-head"><div><span className="eyebrow">GARMIN CONNECT</span><h1>{bi(lang,"Garmin synchronisieren","Sync Garmin")}</h1><p className="muted">{bi(lang,"Einfach synchronisieren. PenguCoach holt aktuelle Tageswerte, Aktivitäten und – falls aktiviert – FIT-Daten.","Simply synchronize. PenguCoach fetches current daily metrics, activities and FIT data when enabled.")}</p></div><span className={`connection-pill ${status?.connected?"online":"offline"}`}><i/>{status?.connected?bi(lang,"Verbunden","Connected"):bi(lang,"Nicht verbunden","Not connected")}</span></div>

    {msg&&<div className="ai-toast">{msg}</div>}

    {status?.connected&&<section className="card garmin-sync-card"><div className="garmin-account"><div className="garmin-device-mark">G</div><div><span className="metric-label">Account</span><strong>{status.display_name??"Garmin Connect"}</strong><small>{bi(lang,"Nur-Lese-Verbindung","Read-only connection")}</small></div></div><div className="garmin-sync-meta"><div><small>{bi(lang,"Letzter Sync","Last sync")}</small><strong>{status.last_successful_sync_at?new Date(status.last_successful_sync_at).toLocaleString():"—"}</strong></div><div><small>{bi(lang,"Nächster Sync","Next sync")}</small><strong>{status.next_sync_at?new Date(status.next_sync_at).toLocaleString():"—"}</strong></div></div><button className="garmin-sync-primary" disabled={syncing} onClick={sync}>{syncing?bi(lang,"Wird gestartet…","Starting…"):bi(lang,"Synchronisieren","Synchronize")}</button></section>}

    {!status?.connected&&!challenge&&<form className="card stack" onSubmit={connect}><div><span className="eyebrow">CONNECTION</span><h2>{bi(lang,"Garmin verbinden","Connect Garmin")}</h2><p className="muted">{bi(lang,"Das Passwort wird nur für die Garmin-Anmeldung verwendet und nicht dauerhaft gespeichert.","The password is used only for Garmin sign-in and is not stored persistently.")}</p></div><label>E-Mail<input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{bi(lang,"Passwort","Password")}<input type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label><button>{bi(lang,"Verbinden","Connect")}</button></form>}
    {challenge&&<form className="card stack" onSubmit={mfa}><h2>MFA / Zwei-Faktor-Bestätigung</h2><p>{bi(lang,"Gib den von Garmin angeforderten Code ein.","Enter the verification code requested by Garmin.")}</p><label>Code<input required value={code} onChange={e=>setCode(e.target.value)}/></label><button>{bi(lang,"Bestätigen","Verify")}</button></form>}

    {status?.connected&&status.settings&&<section className="card garmin-settings-card"><div className="section-heading"><div><span className="eyebrow">AUTOMATION</span><h2>{bi(lang,"Automatische Synchronisierung","Automatic synchronization")}</h2><p className="muted">{bi(lang,"Diese Einstellungen laufen im Hintergrund. Für den Alltag reicht der Button „Synchronisieren“ oben.","These settings run in the background. For everyday use, the Synchronize button above is enough.")}</p></div><span className="badge">{status.settings.enabled?"AUTO ON":"AUTO OFF"}</span></div><div className="garmin-setting-grid"><label>{bi(lang,"Intervall","Interval")}<select value={status.settings.interval_minutes} onChange={e=>setStatus({...status,settings:{...status.settings!,interval_minutes:Number(e.target.value)}})}><option value={15}>15 min</option><option value={30}>30 min</option><option value={60}>1 h</option><option value={120}>2 h</option><option value={360}>6 h</option><option value={720}>12 h</option><option value={1440}>24 h</option></select></label><div className="garmin-toggle-stack"><label className="switch-row"><input type="checkbox" checked={status.settings.enabled} onChange={e=>setStatus({...status,settings:{...status.settings!,enabled:e.target.checked}})}/><span/><div><strong>{bi(lang,"Automatischer Sync","Automatic sync")}</strong><small>{bi(lang,"Regelmäßig neue Garmin-Daten holen","Regularly fetch new Garmin data")}</small></div></label><label className="switch-row"><input type="checkbox" checked={status.settings.fit_download_enabled} onChange={e=>setStatus({...status,settings:{...status.settings!,fit_download_enabled:e.target.checked}})}/><span/><div><strong>Original FIT</strong><small>{bi(lang,"FIT-Dateien neuer Aktivitäten laden","Download FIT files for new activities")}</small></div></label><label className="switch-row"><input type="checkbox" checked={status.settings.fit_analysis_enabled} onChange={e=>setStatus({...status,settings:{...status.settings!,fit_analysis_enabled:e.target.checked}})}/><span/><div><strong>{bi(lang,"FIT analysieren","Analyze FIT")}</strong><small>{bi(lang,"Zeitreihen und Trainingsmetriken erzeugen","Generate time series and training metrics")}</small></div></label></div></div><div className="form-actions"><button onClick={saveSettings}>{bi(lang,"Einstellungen speichern","Save settings")}</button><button className="ghost" onClick={disconnect}>{bi(lang,"Garmin trennen","Disconnect Garmin")}</button></div></section>}

    {status?.connected&&status.settings&&<section className="card garmin-history-card"><button type="button" className="garmin-history-toggle" onClick={()=>setHistoryOpen(v=>!v)}><div><span className="eyebrow">HISTORY</span><strong>{bi(lang,"Historie & Ersteinrichtung","History & initial setup")}</strong><small>{bi(lang,"Nur nötig, wenn du ältere Daten nachladen oder den Historienzeitraum ändern möchtest.","Only needed when you want to backfill older data or change the history range.")}</small></div><span>{historyOpen?"−":"+"}</span></button>{historyOpen&&<div className="garmin-history-body"><label>{bi(lang,"Zeitraum","Period")}<select value={status.settings.historical_days} onChange={e=>setStatus({...status,settings:{...status.settings!,historical_days:Number(e.target.value)}})}><option value={30}>30 {bi(lang,"Tage","days")}</option><option value={90}>90 {bi(lang,"Tage","days")}</option><option value={365}>1 {bi(lang,"Jahr","year")}</option><option value={730}>2 {bi(lang,"Jahre","years")}</option><option value={1825}>5 {bi(lang,"Jahre","years")}</option></select></label><p className="muted">{bi(lang,"Der Historienimport fragt viele Garmin-Tage ab und kann länger dauern. Für normale tägliche Updates nicht verwenden.","History import requests many Garmin days and can take a while. It is not needed for normal daily updates.")}</p><button className="ghost" onClick={startImport}>{bi(lang,"Historie jetzt nachladen","Backfill history now")}</button></div>}</section>}

    {status?.last_error_code&&<section className="card subtle"><strong className="status-warn">{status.last_error_code}</strong></section>}
  </AppShell>
}
