"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import AppShell from "../../../components/AppShell";
import {api} from "../../../lib/api";
import {bi,useI18n} from "../../../lib/i18n";

type Provider={id:string;name:string;provider_type:string;base_url?:string;enabled:boolean;is_local:boolean;has_secret?:boolean};
type Model={id:string;provider_id:string;provider_name?:string;provider_type?:string;local?:boolean;model_identifier:string;display_name:string;enabled:boolean;context_window?:number;provider_max_output_tokens?:number;temperature:number};
type Discovery={id:string;display_name?:string;context_window?:number;max_output_tokens?:number};
type Privacy={local_ai_only:boolean;cloud_health_ai_allowed:boolean};
type Route={task_type:string;primary_model_id:string|null;fallback_model_id:string|null;enabled:boolean;max_output_tokens:number;context_window_tokens:number;max_context_chars:number;default_prompt:string;default_prompt_de:string;default_prompt_en:string;factory_prompt_de:string;factory_prompt_en:string};

const TASKS=["coach_chat","activity_analysis","training_plan"];
const taskName=(task:string,de:boolean)=>({coach_chat:de?"Coach Chat":"Coach chat",activity_analysis:de?"Aktivitätsanalyse":"Activity analysis",training_plan:de?"Trainingsplanung":"Training planning"}[task]??task);
const taskSub=(task:string,de:boolean)=>({coach_chat:de?"Freier Chat mit intelligentem Trainingskontext":"Free chat with smart training context",activity_analysis:de?"Tiefe Einheitenanalyse mit frei wählbarem Kontext":"Deep session analysis with configurable context",training_plan:de?"Periodisierte Pläne aus Ziel und Trainingsdaten":"Periodized plans from goals and training data"}[task]??"");
const taskIcon=(task:string)=>task==="coach_chat"?"✦":task==="activity_analysis"?"⌁":"◫";
const recommended:{[k:string]:{ctx:number;out:number}}={coach_chat:{ctx:8192,out:2500},activity_analysis:{ctx:16384,out:8000},training_plan:{ctx:16384,out:8000}};

export default function AIAdmin(){
  const{lang}=useI18n();const de=lang!=="en";
  const[p,setP]=useState<Provider[]>([]),[m,setM]=useState<Model[]>([]),[routes,setRoutes]=useState<Route[]>([]),[msg,setMsg]=useState("");
  const[privacy,setPrivacy]=useState<Privacy|null>(null);
  const[type,setType]=useState("ollama"),[name,setName]=useState("Local Ollama"),[url,setUrl]=useState("http://127.0.0.1:11434"),[key,setKey]=useState("");
  const[found,setFound]=useState<Discovery[]>([]),[foundProviderId,setFoundProviderId]=useState(""),[selectedTask,setSelectedTask]=useState("activity_analysis"),[promptLang,setPromptLang]=useState<"de"|"en">(de?"de":"en"),[infraOpen,setInfraOpen]=useState(false),[editing,setEditing]=useState<Model|null>(null);
  const refresh=()=>{void Promise.all([api<Provider[]>("/admin/ai/providers"),api<Model[]>("/admin/ai/models"),api<Route[]>("/admin/ai/routes"),api<Privacy>("/settings/privacy")]).then(([pp,mm,rr,pr])=>{setP(pp);setM(mm);setRoutes(rr);setPrivacy(pr)})};
  useEffect(refresh,[]);useEffect(()=>setPromptLang(de?"de":"en"),[de]);
  async function create(e:FormEvent){
    e.preventDefault();
    const external=type!=="ollama";
    await api("/admin/ai/providers",{method:"POST",body:JSON.stringify({name,provider_type:type,base_url:url||null,api_key:key||null,is_local:type==="ollama"})});
    setKey("");
    if(external&&privacy&&(privacy.local_ai_only||!privacy.cloud_health_ai_allowed))setMsg(de?"Provider gespeichert · Cloud-KI ist für Gesundheits- und Trainingsdaten noch nicht freigegeben":"Provider saved · cloud AI is not yet permitted for health and training data");
    else setMsg(de?"Provider gespeichert":"Provider saved");
    refresh();
  }
  function applyDiscovery(r:any,providerId=""){const details=(r.model_details??[]).map((x:any)=>({id:x.id,display_name:x.display_name,context_window:x.context_window,max_output_tokens:x.max_output_tokens}));setFound(details.length?details:(r.models??[]).map((x:string)=>({id:x,display_name:x})));setFoundProviderId(providerId);setMsg(`${r.ok?"✓":"!"} ${(r.models??[]).length} ${de?"Modelle erkannt":"models detected"}`)}
  async function test(){try{const r=await api<any>("/admin/ai/providers/test",{method:"POST",body:JSON.stringify({name,provider_type:type,base_url:url||null,api_key:key||null,is_local:type==="ollama"})});const matched=p.find(x=>x.provider_type===type&&x.base_url===url);applyDiscovery(r,matched?.id??"")}catch(e){setMsg(e instanceof Error?e.message:String(e))}}
  async function discoverSaved(provider:Provider){try{const r=await api<any>(`/admin/ai/providers/${provider.id}/discover`,{method:"POST"});applyDiscovery(r,provider.id)}catch(e){setMsg(e instanceof Error?e.message:String(e))}}
  async function addModel(providerId:string,item?:Discovery){const id=item?.id??prompt("Model identifier / Modell-ID")??"";if(!id)return;await api("/admin/ai/models",{method:"POST",body:JSON.stringify({provider_id:providerId,model_identifier:id,display_name:item?.display_name||id,context_window:item?.context_window||null,provider_max_output_tokens:item?.max_output_tokens||null,temperature:.2,enabled:true})});setMsg(de?"Modell hinzugefügt":"Model added");refresh()}
  async function saveModel(model:Model){await api(`/admin/ai/models/${model.id}`,{method:"PUT",body:JSON.stringify({model_identifier:model.model_identifier,display_name:model.display_name,context_window:model.context_window||null,provider_max_output_tokens:model.provider_max_output_tokens||null,temperature:model.temperature,enabled:model.enabled})});setEditing(null);setMsg(de?"Modell gespeichert":"Model saved");refresh()}
  async function deleteModel(model:Model){if(!confirm(`${de?"Modell löschen":"Delete model"}: ${model.display_name}?`))return;await api(`/admin/ai/models/${model.id}`,{method:"DELETE"});setMsg(de?"Modell gelöscht":"Model deleted");refresh()}
  async function deleteProvider(provider:Provider){if(!confirm(`${de?"Provider und zugehörige Modelle löschen":"Delete provider and its models"}: ${provider.name}?`))return;await api(`/admin/ai/providers/${provider.id}`,{method:"DELETE"});setMsg(de?"Provider gelöscht":"Provider deleted");refresh()}
  async function enableCloudAI(){await api("/settings/privacy",{method:"PUT",body:JSON.stringify({local_ai_only:false,cloud_health_ai_allowed:true})});setPrivacy({local_ai_only:false,cloud_health_ai_allowed:true});setMsg(de?"Cloud-KI für Gesundheits- und Trainingsdaten aktiviert":"Cloud AI enabled for health and training data")}
  function patchRoute(task:string,patch:Partial<Route>){setRoutes(v=>v.map(r=>r.task_type===task?{...r,...patch}:r))}
  function patchBudget(r:Route,patch:Partial<Route>){const next={...r,...patch};const input=Math.max(512,next.context_window_tokens-next.max_output_tokens-1024);next.max_context_chars=Math.max(4000,Math.floor(input*.72)*4);patchRoute(r.task_type,next)}
  async function saveRoute(r:Route){await api(`/admin/ai/routes/${r.task_type}`,{method:"PUT",body:JSON.stringify(r)});setMsg(`${taskName(r.task_type,de)} · ${de?"gespeichert":"saved"}`);refresh()}
  const cloudConfigured=p.some(x=>x.enabled&&!x.is_local);
  const cloudAllowed=Boolean(privacy&&!privacy.local_ai_only&&privacy.cloud_health_ai_allowed);
  const cloudBlocked=cloudConfigured&&Boolean(privacy&&!cloudAllowed);
  const externalProviderSelected=type!=="ollama";
  const discoveryProvider=p.find(x=>x.id===foundProviderId);
  const route=routes.find(r=>r.task_type===selectedTask);const activeModels=m.filter(x=>x.enabled);const selectedModel=activeModels.find(x=>x.id===route?.primary_model_id);
  const budget=useMemo(()=>{if(!route)return{input:0,pctOut:0,pctInput:0};const input=Math.max(0,route.context_window_tokens-route.max_output_tokens-1024);return{input,pctOut:Math.min(100,route.max_output_tokens/route.context_window_tokens*100),pctInput:Math.min(100,input/route.context_window_tokens*100)}},[route]);
  const rec=recommended[selectedTask]||recommended.activity_analysis;
  return <AppShell>
    <div className="ai-studio-head"><div><span className="eyebrow">PENGUCOACH AI STUDIO</span><h1>{bi(lang,"AI & Modelle","AI & models")}</h1><p className="muted">{bi(lang,"Modelle, Kontext, Antwortlänge und Prompts – frei konfigurierbar mit sinnvollen Empfehlungen.","Models, context, response length and prompts — fully configurable with sensible recommendations.")}</p></div><div className="ai-studio-kpis"><div><strong>{activeModels.length}</strong><span>{bi(lang,"aktive Modelle","active models")}</span></div><div><strong>{p.filter(x=>x.enabled).length}</strong><span>Provider</span></div><div title={bi(lang,"Wie viele AI-Aufgaben ein fest gewähltes Standardmodell haben. Ohne feste Zuweisung verwendet PenguCoach automatisch das erste aktive Modell.","How many AI tasks have an explicitly selected default model. Without a fixed assignment PenguCoach automatically uses the first active model.")}><strong>{routes.filter(x=>x.primary_model_id).length}/{routes.length}</strong><span>{bi(lang,"Feste Modelle ⓘ","fixed models ⓘ")}</span></div></div></div>
    {msg&&<div className="ai-toast">{msg}</div>}
    {cloudBlocked&&<div className="cloud-ai-consent"><div><strong>{bi(lang,"Externes KI-Modell erkannt","External AI model detected")}</strong><span>{bi(lang,"Cloud-Modelle wie Claude oder OpenAI dürfen Gesundheits- und Trainingsdaten erst nach deiner ausdrücklichen Freigabe erhalten. Ohne Freigabe bleiben sie im Coach ausgeblendet.","Cloud models such as Claude or OpenAI may receive health and training data only after your explicit permission. Without permission they remain hidden in the Coach.")}</span></div><div><button type="button" onClick={enableCloudAI}>{bi(lang,"Cloud-KI aktivieren","Enable cloud AI")}</button><a className="ghost button-like" href="/settings/privacy">{bi(lang,"Datenschutz öffnen","Open privacy")}</a></div></div>}
    <section className="ai-task-switcher">{TASKS.map(t=><button type="button" key={t} className={selectedTask===t?"active":""} onClick={()=>setSelectedTask(t)}><span>{taskIcon(t)}</span><div><strong>{taskName(t,de)}</strong><small>{taskSub(t,de)}</small></div></button>)}</section>
    {route&&<section className="card ai-config-shell"><div className="ai-config-top"><div><span className="badge">{route.task_type}</span><h2>{taskName(route.task_type,de)}</h2><p className="muted">{taskSub(route.task_type,de)}</p></div><button onClick={()=>saveRoute(route)}>{bi(lang,"Änderungen speichern","Save changes")}</button></div>
      <div className="ai-config-grid"><div className="ai-config-section"><div className="ai-section-title"><span>01</span><div><strong>{bi(lang,"Modell-Routing","Model routing")}</strong><small>{bi(lang,"Standard- und Fallback-Modell pro Aufgabe.","Default and fallback model per task.")}</small></div></div><label>{bi(lang,"Standardmodell","Default model")}<select value={route.primary_model_id??""} onChange={e=>patchRoute(route.task_type,{primary_model_id:e.target.value||null})}><option value="">{bi(lang,"Automatisch erstes aktives Modell","Automatically first active model")}</option>{activeModels.map(x=><option key={x.id} value={x.id}>{x.display_name} · {x.provider_name} · {x.local?"LOCAL":"CLOUD"}</option>)}</select></label><label>Fallback<select value={route.fallback_model_id??""} onChange={e=>patchRoute(route.task_type,{fallback_model_id:e.target.value||null})}><option value="">—</option>{activeModels.map(x=><option key={x.id} value={x.id}>{x.display_name} · {x.provider_name}</option>)}</select></label><div className="ai-selected-model"><span className={`ai-local-dot ${selectedModel?.local?"local":"cloud"}`}/><div><strong>{selectedModel?.display_name??bi(lang,"Automatische Auswahl","Automatic selection")}</strong><small>{selectedModel?.provider_name??""}{selectedModel?.context_window?` · ${selectedModel.context_window.toLocaleString()} ctx`:""}</small></div></div></div>
      <div className="ai-config-section"><div className="ai-section-title"><span>02</span><div><strong>{bi(lang,"Kontext & Antwort","Context & response")}</strong><small>{bi(lang,"Frei wählbar. Empfehlungen können mit einem Klick wiederhergestellt werden.","Fully configurable. Restore recommendations with one click.")}</small></div></div><div className="recommended-strip"><div><strong>{bi(lang,"Empfohlen","Recommended")}</strong><span>{rec.ctx.toLocaleString()} ctx · {rec.out.toLocaleString()} output</span></div><button type="button" className="ghost compact" onClick={()=>patchBudget(route,{context_window_tokens:rec.ctx,max_output_tokens:rec.out})}>{bi(lang,"Übernehmen","Apply")}</button></div><label>{bi(lang,"Kontextfenster","Context window")}<div className="ai-number-control"><input type="number" min={2048} max={1048576} step={1024} value={route.context_window_tokens} onChange={e=>patchBudget(route,{context_window_tokens:Number(e.target.value)})}/><span>tokens</span></div></label><div className="ai-preset-row">{[4096,8192,16384,32768,65536].map(v=><button type="button" className={route.context_window_tokens===v?"active":""} key={v} onClick={()=>patchBudget(route,{context_window_tokens:v})}>{v/1024}K</button>)}</div><label>{bi(lang,"Maximale Antwort","Maximum response")}<div className="ai-number-control"><input type="number" min={128} max={65536} step={1} value={route.max_output_tokens} onChange={e=>patchBudget(route,{max_output_tokens:Number(e.target.value)})}/><span>tokens</span></div></label><div className="ai-preset-row response">{[2500,3500,8000,16000].map(v=><button type="button" className={route.max_output_tokens===v?"active":""} key={v} onClick={()=>patchBudget(route,{max_output_tokens:v})}>{v>=1000?`${v/1000}K`:v}</button>)}</div><div className="ai-budget-viz"><div className="ai-budget-bar"><i className="input" style={{width:`${budget.pctInput}%`}}/><i className="output" style={{width:`${budget.pctOut}%`}}/></div><div className="ai-budget-legend"><span><i className="input"/>≈ {budget.input.toLocaleString()} {bi(lang,"für Input","for input")}</span><span><i className="output"/>{route.max_output_tokens.toLocaleString()} {bi(lang,"für Antwort","for response")}</span><span>{bi(lang,"Reserve","reserve")}: 1024</span></div></div><small>{selectedModel?.local?bi(lang,"Bei Ollama wird das Kontextfenster als num_ctx und die Antwortgrenze als num_predict gesendet.","For Ollama the context window is sent as num_ctx and the response limit as num_predict."):bi(lang,"Bei Cloud-Modellen begrenzt PenguCoach zusätzlich; das Provider-/Modelllimit bleibt maßgeblich.","For cloud models PenguCoach adds a budget; provider/model limits still apply.")}</small></div></div>
      <div className="ai-prompt-section"><div className="ai-section-title"><span>03</span><div><strong>{bi(lang,"System-Prompt der Aufgabe","Task prompt")}</strong><small>{bi(lang,"Deutsch und Englisch separat; automatisch nach UI-Sprache.","German and English separately; selected automatically from UI language.")}</small></div></div><div className="ai-prompt-tabs"><button type="button" className={promptLang==="de"?"active":""} onClick={()=>setPromptLang("de")}>DE</button><button type="button" className={promptLang==="en"?"active":""} onClick={()=>setPromptLang("en")}>EN</button><span/><button type="button" className="ghost" onClick={()=>patchRoute(route.task_type,promptLang==="de"?{default_prompt_de:route.factory_prompt_de}:{default_prompt_en:route.factory_prompt_en})}>{bi(lang,"Standard wiederherstellen","Restore default")}</button></div><textarea className="prompt-editor modern" value={promptLang==="de"?route.default_prompt_de:route.default_prompt_en} onChange={e=>patchRoute(route.task_type,promptLang==="de"?{default_prompt_de:e.target.value}:{default_prompt_en:e.target.value})}/></div>
    </section>}

    <section className="card ai-infra-card">
      <button type="button" className="ai-infra-toggle" onClick={()=>setInfraOpen(v=>!v)}>
        <div><strong>{bi(lang,"Provider & Modelle","Providers & models")}</strong><small>{bi(lang,"Ollama, OpenAI, Claude und OpenAI-kompatible Endpunkte verwalten.","Manage Ollama, OpenAI, Claude and OpenAI-compatible endpoints.")}</small></div><span>{infraOpen?"−":"+"}</span>
      </button>
      {infraOpen&&<div className="ai-infra-body">
        <div className="grid2">
          <form className="stack ai-provider-form" onSubmit={create}>
            <h3>{bi(lang,"Provider hinzufügen / testen","Add / test provider")}</h3>
            <div className="grid2">
              <label>Type<select value={type} onChange={e=>{setType(e.target.value);setFound([]);setFoundProviderId("");if(e.target.value==="ollama")setUrl("http://127.0.0.1:11434");else if(e.target.value==="openai")setUrl("https://api.openai.com/v1");else if(e.target.value==="anthropic")setUrl("https://api.anthropic.com/v1")}}><option value="ollama">Ollama</option><option value="openai">OpenAI</option><option value="anthropic">Anthropic / Claude</option><option value="openai_compatible">OpenAI compatible</option></select></label>
              <label>Name<input value={name} onChange={e=>setName(e.target.value)}/></label>
            </div>
            <label>Base URL<input value={url} onChange={e=>setUrl(e.target.value)}/></label>
            <label>API Key<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder={type==="ollama"?"optional":"required"}/></label>
            {externalProviderSelected&&privacy&&<div className={`cloud-ai-provider-note ${cloudAllowed?"allowed":"blocked"}`}><div><strong>{cloudAllowed?bi(lang,"Cloud-KI freigegeben","Cloud AI permitted"):bi(lang,"Externer KI-Provider","External AI provider")}</strong><span>{cloudAllowed?bi(lang,"Gesundheits- und Trainingsdaten dürfen gemäß deiner Datenschutzeinstellung an externe KI-Provider gesendet werden.","According to your privacy setting, health and training data may be sent to external AI providers."):bi(lang,"Dieser Provider verarbeitet Anfragen außerhalb des PenguCoach-Servers. Gesundheits- und Trainingsdaten bleiben gesperrt, bis du Cloud-KI ausdrücklich freigibst.","This provider processes requests outside the PenguCoach server. Health and training data remains blocked until you explicitly permit cloud AI.")}</span></div>{!cloudAllowed&&<div><button type="button" className="compact" onClick={enableCloudAI}>{bi(lang,"Cloud-KI aktivieren","Enable cloud AI")}</button><a className="ghost button-like compact" href="/settings/privacy">{bi(lang,"Datenschutz","Privacy")}</a></div>}</div>}
            <div className="form-actions"><button type="button" className="ghost" onClick={test}>{bi(lang,"Verbindung testen","Test connection")}</button><button>{bi(lang,"Provider speichern","Save provider")}</button></div>
            {type==="anthropic"&&<small>{bi(lang,"Claude-Modelle werden über Anthropic /v1/models erkannt. Kontext- und Output-Limits werden beim Hinzufügen übernommen.","Claude models are discovered through Anthropic /v1/models. Context and output limits are imported when adding them.")}</small>}
            {found.length>0&&<div className="model-discovery">
              <strong>{bi(lang,"Erkannte Modelle","Detected models")}</strong>
              {!discoveryProvider&&<small>{bi(lang,"Speichere den Provider zuerst oder nutze bei einem vorhandenen Provider „Erkennen“, um Modelle direkt hinzuzufügen.","Save the provider first or use Discover on an existing provider to add models directly.")}</small>}
              <div className="discovery-list">{found.slice(0,60).map(x=><div key={x.id}><div><strong>{x.display_name||x.id}</strong><small>{x.id}{x.context_window?` · ${x.context_window.toLocaleString()} ctx`:""}{x.max_output_tokens?` · ${x.max_output_tokens.toLocaleString()} max out`:""}</small></div><button type="button" className="ghost compact" disabled={!discoveryProvider} onClick={()=>discoveryProvider&&addModel(discoveryProvider.id,x)}>+ {bi(lang,"Hinzufügen","Add")}</button></div>)}</div>
            </div>}
          </form>
          <div><h3>Providers</h3><div className="ai-provider-list">{p.map(x=><div className="ai-provider-row" key={x.id}><span className={`ai-local-dot ${x.is_local?"local":"cloud"}`}/><div><strong>{x.name}</strong><small>{x.provider_type} · {x.base_url??"—"}</small></div><div className="provider-actions"><button className="ghost compact" onClick={()=>discoverSaved(x)}>{bi(lang,"Erkennen","Discover")}</button><button className="ghost compact" onClick={()=>addModel(x.id)}>+ {bi(lang,"Modell","Model")}</button><button className="ghost compact danger-text delete-action" title={bi(lang,"Provider löschen","Delete provider")} aria-label={bi(lang,"Provider löschen","Delete provider")} onClick={()=>deleteProvider(x)}>{bi(lang,"Löschen","Delete")}</button></div></div>)}</div></div>
        </div>
        <div className="model-management"><div className="section-heading"><div><span className="eyebrow">MODELS</span><h3>{bi(lang,"Gespeicherte Modelle","Saved models")}</h3></div></div><div className="model-card-grid">{m.map(x=><div className={`model-card ${x.enabled?"":"disabled"}`} key={x.id}><div className="model-card-head"><span className={`ai-local-dot ${x.local?"local":"cloud"}`}/><div><strong>{x.display_name}</strong><small>{x.provider_name} · {x.provider_type}</small></div><span className="fit-status parsed">{x.enabled?"ON":"OFF"}</span></div><code>{x.model_identifier}</code><div className="model-meta"><span>{x.context_window?`${x.context_window.toLocaleString()} ctx`:"ctx —"}</span><span>{x.provider_max_output_tokens?`${x.provider_max_output_tokens.toLocaleString()} max out`:"output —"}</span></div><div className="form-actions model-actions"><button className="ghost compact" onClick={()=>setEditing({...x})}>{bi(lang,"Bearbeiten","Edit")}</button><button className="ghost compact danger-text delete-action" onClick={()=>deleteModel(x)}>{bi(lang,"Löschen","Delete")}</button></div></div>)}</div></div>
        {editing&&<div className="model-editor"><div className="between"><div><span className="eyebrow">MODEL EDITOR</span><h3>{editing.display_name}</h3></div><button className="ghost compact" onClick={()=>setEditing(null)}>×</button></div><div className="grid2"><label>{bi(lang,"Anzeigename","Display name")}<input value={editing.display_name} onChange={e=>setEditing({...editing,display_name:e.target.value})}/></label><label>Model ID<input value={editing.model_identifier} onChange={e=>setEditing({...editing,model_identifier:e.target.value})}/></label><label>{bi(lang,"Kontextfenster","Context window")}<input type="number" value={editing.context_window??""} placeholder="auto" onChange={e=>setEditing({...editing,context_window:e.target.value?Number(e.target.value):undefined})}/></label><label>{bi(lang,"Provider Max Output","Provider max output")}<input type="number" value={editing.provider_max_output_tokens??""} placeholder="unknown" onChange={e=>setEditing({...editing,provider_max_output_tokens:e.target.value?Number(e.target.value):undefined})}/></label><label>Temperature<input type="number" step="0.1" min="0" max="2" value={editing.temperature} onChange={e=>setEditing({...editing,temperature:Number(e.target.value)})}/></label><label className="row"><input style={{width:20}} type="checkbox" checked={editing.enabled} onChange={e=>setEditing({...editing,enabled:e.target.checked})}/>{bi(lang,"Modell aktiv","Model enabled")}</label></div>{editing.provider_type==="anthropic"&&<small>{bi(lang,"Hinweis: PenguCoach sendet Temperature bei Claude bewusst nicht mit, damit aktuelle Claude-Modelle kompatibel bleiben.","Note: PenguCoach intentionally omits temperature for Claude to stay compatible with current Claude models.")}</small>}<div className="form-actions"><button onClick={()=>saveModel(editing)}>{bi(lang,"Modell speichern","Save model")}</button><button className="ghost" onClick={()=>setEditing(null)}>{bi(lang,"Abbrechen","Cancel")}</button></div></div>}
      </div>}
    </section>
  </AppShell>
}
