"use client";
import {FormEvent,useEffect,useRef,useState} from "react";
import ContextPicker,{defaultContext} from "../../components/ContextPicker";
import CoachPersonal from "../../components/CoachPersonal";
import AppShell from "../../components/AppShell";
import AiReport from "../../components/AiReport";
import TrainingZoneStatus from "../../components/TrainingZoneStatus";
import AiQualityControl from "../../components/AiQualityControl";
import {api} from "../../lib/api";
import {bi,useI18n} from "../../lib/i18n";
import {localDate} from "../../lib/sources";
import {euro,type QualityId} from "../../lib/aiUsage";
type AnyObj=Record<string,any>;
type M={id?:string;role:"user"|"assistant";content:string;metadata?:AnyObj;created_at?:string};
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
function progressTokens(p:AnyObj|null){if(!p)return"";const used=p.output_tokens_exact??p.output_tokens_estimate;return used==null?"":`${p.output_tokens_exact==null?"≈ ":""}${Number(used).toLocaleString()}${p.max_output_tokens?` / ${Number(p.max_output_tokens).toLocaleString()}`:""} Tokens`}
function errorText(error:string,de:boolean){if(error.includes("AI_EMPTY_RESPONSE_THINKING_LIMIT"))return de?"Das Modell hat sein Ausgabelimit verbraucht, ohne eine sichtbare Antwort zu liefern. Der Denkmodus wird bereits abgeschaltet. Prüfe bei diesem benutzerdefinierten Modell das Ollama-Template oder wähle ein anderes Modell.":"The model exhausted its output limit without a visible answer. Thinking is already disabled. Check this custom model's Ollama template or select another model.";if(error.includes("AI_EMPTY_RESPONSE"))return de?"Das Modell hat keine sichtbare Antwort geliefert. Bitte erneut versuchen oder ein anderes Modell wählen.":"The model returned no visible answer. Try again or choose another model.";if(error.includes("CONTEXT_TOO_SMALL"))return de?"Das Kontextfenster ist für die hinterlegten Anweisungen zu klein. Erhöhe es unter Modell & Antwort.":"The context window is too small for the configured instructions. Increase it under Model & response.";return error}
export default function Coach(){
 const {lang}=useI18n(),de=lang!=="en";
 const [text,setText]=useState(""),[msgs,setMsgs]=useState<M[]>([]),[cid,setCid]=useState<string|undefined>(),[title,setTitle]=useState(""),[summary,setSummary]=useState(""),[conversations,setConversations]=useState<AnyObj[]>([]),[historyOpen,setHistoryOpen]=useState(false),[hasMore,setHasMore]=useState(false),[historyMore,setHistoryMore]=useState(false),[historyLoading,setHistoryLoading]=useState(false);
 const [busy,setBusy]=useState(false),[jobText,setJobText]=useState(""),[jobId,setJobId]=useState<string|null>(null),[jobProgress,setJobProgress]=useState<AnyObj|null>(null),[pendingPrompt,setPendingPrompt]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const ignoredJobs=useRef<Set<string>>(new Set()),alive=useRef(true),thread=useRef<HTMLDivElement>(null),restoreId=useRef(0);
 const [caps,setCaps]=useState<AnyObj|null>(null),[model,setModel]=useState(""),[tokens,setTokens]=useState(2500),[ctx,setCtx]=useState(8192),[contextMode,setContextMode]=useState("auto"),[settingsOpen,setSettingsOpen]=useState(false),[settingsCollapsed,setSettingsCollapsed]=useState(false),[isNarrow,setIsNarrow]=useState(false),[quality,setQuality]=useState<QualityId>("standard"),[personal,setPersonal]=useState(true);
 const [contextData,setContextData]=useState(defaultContext);
 const [quick,setQuick]=useState<AnyObj|null>(null),[quickBusy,setQuickBusy]=useState(false);
 const task=caps?.tasks?.coach_chat??{},models=caps?.eligible_models??[],selected=models.find((x:AnyObj)=>x.id===model),modelOutMax=Math.min(Number(selected?.provider_max_output_tokens??65536),65536),modelCtxMax=Math.min(Number(selected?.context_window??1048576),1048576),estimatedInput=Math.max(0,ctx-tokens-1200),budgetPct=Math.min(100,estimatedInput/ctx*100);
 async function loadHistory(append=false){try{const rows=await api<AnyObj[]>(`/coach/conversations?limit=30&offset=${append?conversations.length:0}`);setConversations(v=>append?[...v,...rows]:rows);setHistoryMore(rows.length===30)}catch(e){setError(String(e))}}
 async function openConversation(id:string,older=false){const ticket=++restoreId.current;setHistoryLoading(true);setError("");try{const before=older&&msgs[0]?.created_at?`?before=${encodeURIComponent(msgs[0].created_at)}&before_id=${msgs[0].id}`:"";const c=await api<AnyObj>(`/coach/conversations/${id}${before}`);if(!alive.current||ticket!==restoreId.current)return;setCid(id);setTitle(c.title);setSummary(c.summary||"");setMsgs(v=>older?[...c.messages,...v]:c.messages);setHasMore(c.has_more);localStorage.setItem("pengucoach_conversation",id);if(!older)setHistoryOpen(false)}catch(e){setError(String(e));if(!older)localStorage.removeItem("pengucoach_conversation")}finally{if(ticket===restoreId.current)setHistoryLoading(false)}}
 useEffect(()=>{void api<AnyObj>(`/coach/capabilities?locale=${lang}`).then(c=>{setCaps(c);const t=c.tasks?.coach_chat??{};setModel(t.default_model_id??"");setTokens(t.max_output_tokens??2500);setCtx(t.context_window_tokens??8192);setQuality(t.quality_profile??"standard")}).catch(e=>setError(String(e)))},[lang]);
 useEffect(()=>{alive.current=true;void loadHistory();const query=new URLSearchParams(window.location.search),prompt=query.get("prompt");if(query.get("mode"))setContextMode(query.get("mode")!);const job=localStorage.getItem("pengucoach_coach_job"),id=localStorage.getItem("pengucoach_conversation");async function restore(){if(id)await openConversation(id);if(!alive.current)return;if(job){setBusy(true);setJobId(job);const pending=localStorage.getItem("pengucoach_coach_pending_prompt")||"";setPendingPrompt(pending);void poll(job)}if(prompt){setText(prompt);history.replaceState(null,"","/coach")}}void restore();return()=>{alive.current=false;restoreId.current++}},[]);
 useEffect(()=>{if(thread.current)thread.current.scrollTo({top:thread.current.scrollHeight,behavior:"smooth"})},[msgs.length,jobProgress?.content_preview]);
 useEffect(()=>{const media=window.matchMedia("(max-width:1000px)");const sync=()=>setIsNarrow(media.matches);sync();setSettingsCollapsed(localStorage.getItem("pengucoach_coach_settings_collapsed")==="1");media.addEventListener?.("change",sync);return()=>media.removeEventListener?.("change",sync)},[]);
 async function poll(id:string){setJobText(bi(lang,"Coach denkt…","Coach is thinking…"));for(let i=0;i<1200;i++){if(!alive.current||ignoredJobs.current.has(id))return;try{const j=await api<AnyObj>(`/jobs/${id}`);if(!alive.current||ignoredJobs.current.has(id))return;if(j.ready){localStorage.removeItem("pengucoach_coach_job");localStorage.removeItem("pengucoach_coach_pending_prompt");setBusy(false);setJobId(null);setJobProgress(null);setJobText("");if(j.successful&&j.result?.cancelled){setNotice(bi(lang,"Anfrage abgebrochen.","Request cancelled."));return}if(j.successful&&j.result){const r=j.result;await openConversation(r.conversation_id);await loadHistory();setPendingPrompt("");return}setError(errorText(j.error||"AI job failed",de));return}setJobProgress(j.progress??null);setJobText(j.progress?.message||bi(lang,"Coach denkt…","Coach is thinking…"))}catch(e){setJobText(bi(lang,"Verbindung wird wiederhergestellt…","Reconnecting…"))}await sleep(1000)}setJobText(bi(lang,"Anfrage läuft weiter. Neu laden, um den Status abzurufen.","Request is still running. Reload to check its status."))}
 async function submit(e:FormEvent){e.preventDefault();if(!text.trim()||busy||historyLoading||!model)return;const q=text.trim();setText("");setError("");setNotice("");setPendingPrompt(q);setMsgs(v=>[...v,{role:"user",content:q}]);setBusy(true);setJobProgress(null);localStorage.setItem("pengucoach_coach_pending_prompt",q);try{const r=await api<AnyObj>("/coach/chat/jobs",{method:"POST",body:JSON.stringify({message:q,conversation_id:cid,model_id:model,max_tokens:tokens,context_window_tokens:ctx,context_mode:contextMode,context_data:contextData,use_personal_context:personal,quality_profile:quality,locale:lang})});setCid(r.conversation_id);localStorage.setItem("pengucoach_conversation",r.conversation_id);setJobId(r.task_id);localStorage.setItem("pengucoach_coach_job",r.task_id);void poll(r.task_id)}catch(e){setBusy(false);setError(errorText(String(e),de));setText(q);localStorage.removeItem("pengucoach_coach_pending_prompt")}}
 async function cancelJob(){if(!jobId)return;const id=jobId;try{await api(`/jobs/${id}/cancel`,{method:"POST"})}catch(e){setError(String(e));return}ignoredJobs.current.add(id);localStorage.removeItem("pengucoach_coach_job");localStorage.removeItem("pengucoach_coach_pending_prompt");setBusy(false);setJobId(null);setJobProgress(null);setJobText("");setText(pendingPrompt);setNotice(bi(lang,"Abgebrochen. Dein Text ist wieder im Eingabefeld.","Cancelled. Your text is back in the composer."))}
 function newConversation(){if(busy)return;restoreId.current++;setHistoryLoading(false);setCid(undefined);setMsgs([]);setText("");setTitle("");setSummary("");setError("");setPendingPrompt("");setHasMore(false);setHistoryOpen(false);localStorage.removeItem("pengucoach_conversation")}
 function toggleSettings(){if(isNarrow){setSettingsOpen(v=>!v);return}setSettingsCollapsed(v=>{const next=!v;localStorage.setItem("pengucoach_coach_settings_collapsed",next?"1":"0");return next})}
 function closeSettings(){if(isNarrow){setSettingsOpen(false);return}setSettingsCollapsed(true);localStorage.setItem("pengucoach_coach_settings_collapsed","1")}
 async function changeQuality(value:QualityId,suggested:number){setQuality(value);setTokens(Math.max(128,Math.min(modelOutMax,suggested)));if(!caps)return;const tasks=caps.tasks??{};try{await api("/settings/ai-preferences",{method:"PUT",body:JSON.stringify({coach_chat:value,activity_analysis:tasks.activity_analysis?.quality_profile??"standard",training_plan:tasks.training_plan?.quality_profile??"standard",monthly_budget_eur:caps.monthly_budget_eur??null})})}catch(e){setError(String(e))}}
 async function remember(content:string){const value=window.prompt(bi(lang,"Was soll dauerhaft gespeichert werden? Prüfe und bearbeite den Merksatz.","What should be saved? Review and edit the memory."),content.slice(0,1000));if(!value?.trim())return;try{await api("/coach/memories",{method:"POST",body:JSON.stringify({content:value})});setNotice(bi(lang,"Merksatz gespeichert. Unter „Dein Coach kennt dich“ bearbeitbar.","Memory saved. Editable under ‘Your coach knows you’."));window.dispatchEvent(new Event("coach-memory-updated"))}catch(e){setError(String(e))}}
 function details(m:M){
  const meta=m.metadata||{},u=meta.usage||{},used=meta.evidence||{},inv=used.inventory||{},weather=used.weather||null,readiness=used.readiness||null,trainingLoad=used.training_load||null;
  const dataBits=[inv.activity_count!=null?`${inv.activity_count} ${bi(lang,"Aktivitäten","activities")}`:null,inv.health_days!=null?`${inv.health_days} ${bi(lang,"Tageswerte","daily records")}`:null].filter(Boolean);
  const chips=[
   inv.activity_count>0?`✓ ${bi(lang,"Training","Training")}`:null,
   inv.sleep_days>0?`✓ ${bi(lang,"Schlaf","Sleep")}`:null,
   inv.hrv_days>0?"✓ HRV":null,
   inv.health_days>0?`✓ ${bi(lang,"Erholung","Recovery")}`:null,
   readiness?`✓ Readiness${readiness.score!=null?` ${readiness.score}`:""}`:null,
   trainingLoad?`✓ ${bi(lang,"Belastung","Load")}${trainingLoad.trend?` · ${trainingLoad.trend}`:""}`:null,
   used.upcoming_sessions>0?`✓ ${bi(lang,"Plan","Plan")}`:null,
   used.personal_context?`✓ ${bi(lang,"Profil","Profile")}`:null,
   used.training_zones?`✓ ${bi(lang,"Zonen","Zones")}`:null,
   weather?`${weather.available?"✓":"⚠"} ${bi(lang,"Wetter","Weather")}`:null,
  ].filter(Boolean) as string[];
  const current=weather?.current||{};
  const weatherValues=[current.temperature_2m!=null?`${Math.round(Number(current.temperature_2m))} °C`:null,current.precipitation!=null?`${current.precipitation} mm ${bi(lang,"Niederschlag","precipitation")}`:null,current.wind_speed_10m!=null?`${Math.round(Number(current.wind_speed_10m))} km/h ${bi(lang,"Wind","wind")}`:null,current.wind_gusts_10m!=null?`${Math.round(Number(current.wind_gusts_10m))} km/h ${bi(lang,"Böen","gusts")}`:null].filter(Boolean);
  return <details className="message-evidence"><summary>{bi(lang,"Verwendete Daten & Antwortdetails","Data used & response details")}</summary>{chips.length>0&&<div className="message-context-chips">{chips.map((x,i)=><span key={`${x}-${i}`}>{x}</span>)}</div>}<p>{dataBits.join(" · ")}{used.from?` · ${used.from} – ${used.to}`:""}</p><p>{used.personal_context?bi(lang,"Persönliche Angaben einbezogen.","Personal statements included."):bi(lang,"Ohne persönliches Profil.","No personal profile.")} {used.conversation_summary&&bi(lang,"Frühere Gesprächsauszüge einbezogen.","Earlier conversation excerpts included.")}</p>{weather&&<div className="message-evidence-row weather"><b>{bi(lang,"Wetterkontext","Weather context")}</b><span>{weather.available?(weatherValues.join(" · ")||bi(lang,"Forecast geladen","Forecast loaded")):bi(lang,"Beim Abruf nicht verfügbar – es wurden keine Wetterwerte erfunden.","Unavailable during fetch — no weather values were invented.")}</span><small>{[weather.provider,weather.location,weather.fetched_at?`${bi(lang,"Abruf","fetched")}: ${new Date(weather.fetched_at).toLocaleString()}`:null,weather.forecast_days?`${weather.forecast_days}d Forecast`:null].filter(Boolean).join(" · ")}</small></div>}{[...(used.daily_values||[]),...(used.sleep||[]),...(used.hrv||[])].map((r:AnyObj,i:number)=><div className="message-evidence-row" key={i}><b>{r.date}</b><span>{Object.entries(r).filter(([k,v])=>!["date","sources","source"].includes(k)&&v!=null&&typeof v!=="object").map(([k,v])=>`${k}: ${v}`).join(" · ")}</span><small>{Object.values(r.sources||{}).length?Array.from(new Set(Object.values(r.sources))).join(" + "):r.source}</small></div>)}<small>{meta.model||""} · {u.input_tokens??"?"} in / {u.output_tokens??"?"} out {meta.cost_eur!=null?` · ${euro(meta.cost_eur)}`:""}{meta.context_truncated?` · ${bi(lang,"Kontext verdichtet","Context compacted")}`:""}</small></details>
 }
 return <AppShell><div className="coach-modern-head fitness-coach-head"><div><span className="eyebrow">✦ PENGUCOACH</span><h1>{bi(lang,"Dein Coach. Dein Rhythmus.","Your coach. Your rhythm.")}</h1><p className="muted">{bi(lang,"Gemeinsam verstehen, was dir guttut – mit deinem Alltag, deinen Zielen und deinen Daten.","Find what works for you — with your routines, goals and data.")}</p></div><div className="coach-model-chip"><span className={`ai-local-dot ${selected?.local?"local":"cloud"}`}/><div><small>{bi(lang,"An deiner Seite","By your side")}</small><strong>{selected?.display_name??task.default_model??"—"}</strong><span>{selected?.provider??""}</span></div></div></div>
 <CoachPersonal/><ContextPicker value={contextData} onChange={setContextData} days={contextMode==="none"?0:contextMode==="auto"?7:Number(contextMode)} disabled={busy}/>
 <div className={`coach-layout ${settingsCollapsed?"settings-collapsed":""}`}><section className="card coach-thread"><div className="coach-thread-top"><div><strong>{title||bi(lang,"Lass uns sprechen","Let's talk")}</strong><small>{bi(lang,"Gespräch wird gespeichert","Conversation is saved")}</small></div><div className="companion-actions"><button className="ghost compact" disabled={busy} onClick={()=>setHistoryOpen(!historyOpen)} aria-expanded={historyOpen}>{bi(lang,"Verlauf","History")}</button><button className="ghost compact" disabled={busy} onClick={newConversation}>+ {bi(lang,"Neu","New")}</button></div></div>
 {historyOpen&&<div className="conversation-history"><h3>{bi(lang,"Deine Gespräche","Your conversations")}</h3>{conversations.map(c=><div key={c.id}><button className={`ghost ${c.id===cid?"active":""}`} onClick={()=>openConversation(c.id)}><strong>{c.title}</strong><small>{new Date(c.updated_at).toLocaleDateString()}</small></button><button className="ghost compact" aria-label={bi(lang,"Gespräch umbenennen","Rename conversation")} onClick={async()=>{const name=prompt(bi(lang,"Gesprächstitel","Conversation title"),c.title);if(name)try{await api(`/coach/conversations/${c.id}`,{method:"PATCH",body:JSON.stringify({content:name})});await loadHistory();if(cid===c.id)setTitle(name)}catch(e){setError(String(e))}}}>✎</button><button className="ghost compact danger" aria-label={bi(lang,"Gespräch löschen","Delete conversation")} onClick={async()=>{if(!confirm(bi(lang,"Dieses Gespräch mit allen Nachrichten löschen?","Delete this conversation and all its messages?")))return;try{await api(`/coach/conversations/${c.id}`,{method:"DELETE"});if(cid===c.id)newConversation();await loadHistory()}catch(e){setError(String(e))}}}>×</button></div>)}{!conversations.length&&<p>{bi(lang,"Hier erscheinen deine gespeicherten Gespräche.","Your saved conversations will appear here.")}</p>}{historyMore&&<button className="ghost" onClick={()=>loadHistory(true)}>{bi(lang,"Weitere laden","Load more")}</button>}</div>}
 <div className="coach-messages" ref={thread} aria-live="polite">{hasMore&&<button className="ghost compact" disabled={historyLoading} onClick={()=>cid&&openConversation(cid,true)}>{bi(lang,"Ältere Nachrichten laden","Load older messages")}</button>}{summary&&<details className="conversation-summary"><summary>{bi(lang,"Kompakter Rückblick auf frühere Nachrichten","Compact recap of earlier messages")}</summary><p>{summary}</p><small>{bi(lang,"Gekürzte Originalauszüge; dauerhafte Angaben bitte als Merksatz speichern.","Abbreviated original excerpts; save lasting information as a memory.")}</small></details>}{msgs.length?msgs.map((m,i)=><div key={m.id||i} className={`coach-message ${m.role}`}><div className="coach-message-role">{m.role==="user"?bi(lang,"Du","You"):"✦ PenguCoach"}</div><div className="coach-message-body">{m.role==="assistant"?<AiReport content={m.content||bi(lang,"Diese ältere Antwort enthält keinen sichtbaren Text.","This older response has no visible text.")}/>:m.content}</div>{m.metadata?.truncated&&<div className="ai-truncated-warning">{bi(lang,"Das Modell hat die Antwort am Ausgabelimit beendet.","The model ended this answer at the output limit.")} <button className="ghost compact" onClick={()=>setText(bi(lang,"Bitte führe deine letzte Antwort kurz zu Ende. Wiederhole den bisherigen Text nicht.","Please briefly finish your last answer without repeating it."))}>{bi(lang,"Fortsetzen","Continue")}</button></div>}{m.role==="assistant"&&m.content&&<><div className="message-actions"><button disabled={busy} onClick={()=>setText(bi(lang,"Bitte beantworte das kürzer und konkreter.","Please make that shorter and more specific."))}>{bi(lang,"Kürzer","Shorter")}</button><button disabled={busy} onClick={()=>setText(bi(lang,"Welche Alternative ohne Geräte passt dazu?","What alternative without equipment would work?"))}>{bi(lang,"Alternative","Alternative")}</button><button disabled={busy} onClick={()=>setQuick({date:localDate(),name:bi(lang,"Meine Coach-Einheit","My coach session"),sport:"walking",duration_min:30,notes:m.content.slice(0,1500)})}>{bi(lang,"In Kalender übernehmen","Add to calendar")}</button></div>{details(m)}</>}{m.role==="user"&&<button className="remember-message" onClick={()=>remember(m.content)}>{bi(lang,"Als Merksatz speichern","Save as a memory")}</button>}</div>):!busy&&<div className="coach-empty"><div className="coach-orb">✦</div><h2>{bi(lang,"Was bewegt dich heute?","What's on your mind today?")}</h2><p>{bi(lang,"Eine kurze Frage genügt. Gemeinsam finden wir den nächsten passenden Schritt.","Start with a quick question. Let's find your next step together.")}</p><div className="coach-suggestions">{(de?["Was soll ich heute trainieren?","Wie war meine Trainingswoche?","Ich habe heute nur 30 Minuten."]:["What should I train today?","How was my training week?","I only have 30 minutes today."]).map(x=><button className="ghost" key={x} onClick={()=>setText(x)}>{x} ↗</button>)}</div></div>}
 {busy&&<div className="coach-message assistant pending"><div className="coach-message-role">✦ PenguCoach</div><div className="coach-message-body">{jobProgress?.content_preview?<AiReport content={jobProgress.content_preview}/>:<span className="typing-dots"><i/><i/><i/>{bi(lang,"Ich schaue auf deine Daten…","Looking at your data…")}</span>}</div><small>{jobText} {progressTokens(jobProgress)}</small><button className="ghost danger compact" onClick={cancelJob} disabled={!jobId}>{bi(lang,"Abbrechen","Cancel")}</button></div>}</div>
 {error&&<div className="coach-error" role="alert">{error}{pendingPrompt&&!busy&&<button className="ghost" onClick={()=>setText(pendingPrompt)}>{bi(lang,"Frage erneut verwenden","Reuse question")}</button>}</div>}{notice&&<p className="coach-notice" role="status">{notice}</p>}
 {quick&&<form className="quick-session-form" onSubmit={async e=>{e.preventDefault();setQuickBusy(true);try{await api("/coach/quick-session",{method:"POST",body:JSON.stringify(quick)});setQuick(null);setNotice(bi(lang,"Einheit im Trainingskalender gespeichert.","Session saved in the training calendar."))}catch(e){setError(String(e))}finally{setQuickBusy(false)}}}><strong>{bi(lang,"Einheit prüfen und vormerken","Review and schedule a session")}</strong><p className="muted">{bi(lang,"Lege die konkreten Angaben fest. Es erfolgt kein automatischer Garmin-Export.","Set the session details. This does not export to Garmin automatically.")}</p><div className="personal-grid"><label>{bi(lang,"Name","Name")}<input maxLength={120} required value={quick.name} onChange={e=>setQuick({...quick,name:e.target.value})}/></label><label>{bi(lang,"Datum","Date")}<input type="date" required value={quick.date} onChange={e=>setQuick({...quick,date:e.target.value})}/></label><label>{bi(lang,"Sportart","Sport")}<select aria-label={bi(lang,"Sportart","Sport")} value={quick.sport} onChange={e=>setQuick({...quick,sport:e.target.value})}>{([['walking','Gehen','Walking'],['cycling','Radfahren','Cycling'],['running','Laufen','Running'],['swimming','Schwimmen','Swimming'],['strength','Kraft','Strength'],['mobility','Mobilität','Mobility'],['hiking','Wandern','Hiking'],['yoga','Yoga','Yoga'],['other','Andere','Other']]).map(([k,d,en])=><option key={k} value={k}>{bi(lang,d,en)}</option>)}</select></label><label>{bi(lang,"Dauer (Minuten)","Duration (minutes)")}<input type="number" min={5} max={240} required value={quick.duration_min} onChange={e=>setQuick({...quick,duration_min:Number(e.target.value)})}/></label></div><div className="companion-actions"><button disabled={quickBusy}>{bi(lang,"Im Kalender speichern","Save to calendar")}</button><button type="button" className="ghost" onClick={()=>setQuick(null)}>{bi(lang,"Abbrechen","Cancel")}</button></div></form>}
 <form className="coach-composer" onSubmit={submit}><label className="sr-only" htmlFor="coach-input">{bi(lang,"Deine Nachricht","Your message")}</label><textarea id="coach-input" rows={2} maxLength={8000} value={text} onChange={e=>setText(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey&&!e.nativeEvent.isComposing&&window.matchMedia("(pointer:fine)").matches){e.preventDefault();e.currentTarget.form?.requestSubmit()}}} placeholder={bi(lang,"Frag deinen Coach…","Ask your coach…")}/><div className="coach-composer-actions"><button type="button" className="ghost compact" aria-controls="coach-ai-settings" aria-expanded={isNarrow?settingsOpen:!settingsCollapsed} onClick={toggleSettings}>⚙ {bi(lang,"Modell & Antwort","Model & response")}</button><label className="checkline"><input type="checkbox" checked={personal} disabled={busy} onChange={e=>setPersonal(e.target.checked)}/>{bi(lang,"Mein Profil","My profile")}</label><button disabled={busy||historyLoading||!model||!text.trim()}>{bi(lang,"Senden","Send")} ↑</button></div></form></section>
      <aside id="coach-ai-settings" className={`card coach-side ${settingsOpen?"open":""}`}><div className="between"><div><h2>{bi(lang,"AI Einstellungen","AI settings")}</h2><p className="muted">{bi(lang,"Pro Anfrage anpassbar","Adjustable per request")}</p></div><button type="button" className="ghost compact coach-side-close" onClick={closeSettings} aria-label={bi(lang,"Einstellungen ausblenden","Hide settings")}>×</button></div>
        <label>{bi(lang,"Modell","Model")}<select value={model} onChange={e=>setModel(e.target.value)}>{models.length===0&&<option value="">{bi(lang,"Keine Modelle verfügbar","No models available")}</option>}{models.map((x:AnyObj)=><option value={x.id} key={x.id}>{x.display_name} · {x.provider} · {x.local?"LOCAL":"CLOUD"}</option>)}</select></label>
        {models.length===0&&<div className="cloud-model-empty"><strong>{bi(lang,"Kein freigegebenes KI-Modell","No permitted AI model")}</strong><span>{bi(lang,"Wenn du nur ein externes Modell eingerichtet hast, prüfe die Cloud-KI-Freigabe unter Datenschutz.","If you configured only an external model, check the cloud AI permission under Privacy.")}</span><a href="/settings/privacy">{bi(lang,"Datenschutz öffnen","Open privacy")}</a></div>}
        <label>{bi(lang,"Trainingskontext","Training context")}<select value={contextMode} onChange={e=>setContextMode(e.target.value)}><option value="auto">{bi(lang,"Auto · 7 Tage, Zeitangabe aus Frage","Auto · 7 days, or period in question")}</option><option value="none">{bi(lang,"Kein Kontext","No context")}</option><option value="3">3 {bi(lang,"Tage","days")}</option><option value="14">14 {bi(lang,"Tage","days")}</option><option value="21">21 {bi(lang,"Tage","days")}</option><option value="7">7 {bi(lang,"Tage","days")}</option><option value="28">28 {bi(lang,"Tage","days")}</option></select></label>
        <label>{bi(lang,"Kontextfenster","Context window")}<div className="ai-number-control"><input type="number" min={2048} max={modelCtxMax} step={1024} value={ctx} onChange={e=>setCtx(Math.min(modelCtxMax,Number(e.target.value)))}/><span>tokens</span></div></label>
        <div className="ai-preset-row">{[4096,8192,16384,32768,65536].filter(v=>v<=modelCtxMax).map(v=><button type="button" className={ctx===v?"active":""} key={v} onClick={()=>setCtx(v)}>{v/1024}K</button>)}</div>
        <label>{bi(lang,"Max. Antwort","Max response")}<div className="ai-number-control"><input type="number" min={128} max={modelOutMax} step={1} value={tokens} onChange={e=>setTokens(Math.min(modelOutMax,Number(e.target.value)))}/><span>tokens</span></div></label>
        <AiQualityControl lang={lang} profile={quality} onChange={(v,t)=>void changeQuality(v,t)} options={task.quality_profiles??[]} model={selected} contextWindow={ctx} maxOutput={tokens}/>
        <div className="coach-budget"><div><span>{bi(lang,"Input-Budget","Input budget")}</span><strong>≈ {estimatedInput.toLocaleString()}</strong></div><div><span>{bi(lang,"Antwort","Response")}</span><strong>{tokens.toLocaleString()}</strong></div><div className="coach-budget-track"><i style={{width:`${budgetPct}%`}}/></div></div>
        <small>{selected?.local?bi(lang,"Ollama: Ausgabe wird live gestreamt; Tokenfortschritt ist während der Generierung sichtbar.","Ollama: output is streamed live; token progress is visible while generating."):bi(lang,"Cloud: Tokenlimits begrenzen die Anfrage und helfen Kosten zu kontrollieren.","Cloud: token limits cap the request and help control cost.")}</small>
        {contextData.zones&&contextMode!=="none"&&<TrainingZoneStatus compact/>}
      </aside> </div></AppShell>
}
