"use client";
import {useEffect,useState} from "react";
import {api} from "../lib/api";
import {bi,useI18n} from "../lib/i18n";
export default function ActivityFeedback({activityId}:{activityId:string}){
 const {lang}=useI18n();const [value,setValue]=useState<any>({feeling:"right",exertion:null,comment:""}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{api<any>(`/coach/feedback/${activityId}`).then(v=>{if(v.feeling)setValue(v)}).catch(e=>setMessage(String(e)))},[activityId]);
 return <details className="companion-details"><summary><span className="companion-icon">♡</span><span><strong>{bi(lang,"Wie hat sich das Training angefühlt?","How did that session feel?")}</strong><small>{bi(lang,"Dein Feedback hilft bei den nächsten Empfehlungen","Your feedback informs future suggestions")}</small></span></summary><div className="companion-details-body"><div className="day-chips">{([['easy','Zu leicht','Too easy'],['right','Passend','About right'],['hard','Zu schwer','Too hard']] as const).map(([key,de,en])=><button key={key} aria-pressed={value.feeling===key} className={value.feeling===key?"active":"ghost"} onClick={()=>setValue({...value,feeling:key})}>{bi(lang,de,en)}</button>)}</div><div className="personal-grid"><label>{bi(lang,"Anstrengung (1–10, optional)","Exertion (1–10, optional)")}<input type="number" min={1} max={10} value={value.exertion??""} onChange={e=>setValue({...value,exertion:e.target.value?Number(e.target.value):null})}/></label><label>{bi(lang,"Deine Notiz","Your note")}<textarea maxLength={1000} value={value.comment||""} onChange={e=>setValue({...value,comment:e.target.value})}/></label></div><div className="companion-actions"><button disabled={busy} onClick={async()=>{setBusy(true);try{await api(`/coach/feedback/${activityId}`,{method:"PUT",body:JSON.stringify(value)});setMessage(bi(lang,"Feedback gespeichert.","Feedback saved."))}catch(e){setMessage(String(e))}finally{setBusy(false)}}}>{bi(lang,"Feedback speichern","Save feedback")}</button><button className="ghost" disabled={busy} onClick={async()=>{try{await api(`/coach/feedback/${activityId}`,{method:"DELETE"});setValue({feeling:"right",exertion:null,comment:""});setMessage(bi(lang,"Feedback gelöscht.","Feedback deleted."))}catch(e){setMessage(String(e))}}}>{bi(lang,"Löschen","Delete")}</button></div><p role="status">{message}</p></div></details>
}
