"use client";
import {useEffect,useState} from "react";
import {api} from "../lib/api";
import {bi,useI18n} from "../lib/i18n";
type O=Record<string,any>;
export default function CoachPersonal(){
 const {lang}=useI18n(),de=lang!=="en";const [profile,setProfile]=useState<O|null>(null),[memories,setMemories]=useState<O[]>([]),[draft,setDraft]=useState(""),[editing,setEditing]=useState<string|null>(null),[status,setStatus]=useState(""),[saving,setSaving]=useState(false);
 async function load(){try{const [p,m]=await Promise.all([api<O>("/coach/profile"),api<O[]>("/coach/memories")]);setProfile(p);setMemories(m)}catch(e){setStatus(String(e))}}
 useEffect(()=>{void load();const refresh=()=>void load();window.addEventListener("coach-memory-updated",refresh);return()=>window.removeEventListener("coach-memory-updated",refresh)},[]);
 async function save(){setSaving(true);try{await api("/coach/profile",{method:"PUT",body:JSON.stringify(profile)});setStatus(bi(lang,"Profil gespeichert. Gilt für Coach und Trainingsplanung.","Profile saved. Used for coaching and training plans."))}catch(e){setStatus(String(e))}finally{setSaving(false)}}
 async function remember(){if(!draft.trim())return;setSaving(true);try{await api(`/coach/memories${editing?`/${editing}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify({content:draft})});setDraft("");setEditing(null);await load();setStatus(bi(lang,"Merksatz gespeichert.","Memory saved."))}catch(e){setStatus(String(e))}finally{setSaving(false)}}
 async function remove(id:string){try{await api(`/coach/memories/${id}`,{method:"DELETE"});await load()}catch(e){setStatus(String(e))}}
 return <details className="companion-details personal-details"><summary><span className="companion-icon">✦</span><span><strong>{bi(lang,"Dein Coach kennt dich","Your coach knows you")}</strong><small>{profile?.goal||bi(lang,"Ziele, Alltag & Gedächtnis einrichten","Set up goals, routines & memory")}</small></span><span className="tag">{memories.length} {memories.length===1?bi(lang,"Merksatz","memory"):bi(lang,"Merksätze","memories")}</span></summary><div className="companion-details-body">
 {profile&&<><label className="checkline"><input type="checkbox" checked={profile.enabled!==false} onChange={e=>setProfile({...profile,enabled:e.target.checked})}/>{bi(lang,"Persönliches Profil und Gedächtnis für KI verwenden","Use personal profile and memory for AI")}</label><div className="personal-grid">
 <label>{bi(lang,"Mein Ziel","My goal")}<textarea maxLength={1000} value={profile.goal||""} onChange={e=>setProfile({...profile,goal:e.target.value})} placeholder={bi(lang,"Zum Beispiel: wieder regelmäßig Rad fahren","For example: cycle regularly again")}/></label>
 <label>{bi(lang,"Zieldatum / Wettkampf (optional)","Target / event date (optional)")}<input type="date" value={profile.target_date||""} onChange={e=>setProfile({...profile,target_date:e.target.value||null})}/></label>
 <label>{bi(lang,"Sportarten","Sports")}<input maxLength={300} value={profile.preferred_sports||""} onChange={e=>setProfile({...profile,preferred_sports:e.target.value})}/></label>
 <label>{bi(lang,"Typische Dauer (Minuten)","Usual duration (minutes)")}<input type="number" min={5} max={480} value={profile.session_minutes??45} onChange={e=>setProfile({...profile,session_minutes:Number(e.target.value)})}/></label>
 <label>{bi(lang,"Ausrüstung","Equipment")}<input maxLength={600} value={profile.equipment||""} onChange={e=>setProfile({...profile,equipment:e.target.value})}/></label>
 <label>{bi(lang,"Einschränkungen & Alltag","Constraints & routines")}<textarea maxLength={1000} value={profile.constraints||""} onChange={e=>setProfile({...profile,constraints:e.target.value})}/></label>
 <label>{bi(lang,"Meine Zwischenziele","My milestones")}<textarea maxLength={1000} value={profile.milestones||""} onChange={e=>setProfile({...profile,milestones:e.target.value})} placeholder={bi(lang,"Zum Beispiel: erst 2, später 3 Einheiten pro Woche","For example: first 2, later 3 sessions per week")}/></label>
 <div><label>{bi(lang,"Mögliche Trainingstage","Available training days")}</label><div className="day-chips">{(de?["Mo","Di","Mi","Do","Fr","Sa","So"]:["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]).map((d,i)=><button type="button" className={(profile.training_days||[]).includes(i+1)?"active":"ghost"} aria-pressed={(profile.training_days||[]).includes(i+1)} key={d} onClick={()=>setProfile({...profile,training_days:(profile.training_days||[]).includes(i+1)?profile.training_days.filter((n:number)=>n!==i+1):[...(profile.training_days||[]),i+1]})}>{d}</button>)}</div></div></div><div className="companion-actions"><button disabled={saving} onClick={save}>{bi(lang,"Profil speichern","Save profile")}</button><button className="ghost" onClick={()=>{window.location.href=`/coach?prompt=${encodeURIComponent(de?"Schlage mir anhand meines gespeicherten Ziels und meiner Trainingsdaten drei realistische Zwischenziele vor. Berücksichtige das Zieldatum, falls vorhanden.":"Suggest three realistic milestones using my saved goal and training data, considering the target date if set.")}`}}>{bi(lang,"Zwischenziele mit Coach entwickeln","Develop milestones with Coach")}</button></div></>}
 <div className="memory-section"><h3>{bi(lang,"Das soll sich mein Coach merken","What my coach should remember")}</h3><p className="muted">{bi(lang,"Gespeichert werden deine bestätigten Angaben. Du kannst sie hier jederzeit ändern oder löschen. Neue Angaben im Gespräch haben Vorrang.","Your confirmed statements are saved here. Edit or delete them at any time. New statements in a conversation take priority.")}</p><div className="memory-list">{memories.map(m=><div key={m.id}><p>{m.content}</p><div><button className="ghost compact" onClick={()=>{setDraft(m.content);setEditing(m.id)}}>{bi(lang,"Ändern","Edit")}</button><button className="ghost compact danger" onClick={()=>remove(m.id)}>{bi(lang,"Löschen","Delete")}</button></div></div>)}</div><label>{editing?bi(lang,"Merksatz bearbeiten","Edit memory"):bi(lang,"Neuer Merksatz","New memory")}<textarea maxLength={1000} value={draft} onChange={e=>setDraft(e.target.value)} placeholder={bi(lang,"Mittwochs habe ich keine Zeit für Training.","I have no time to train on Wednesdays.")}/></label><div className="companion-actions"><button disabled={saving||!draft.trim()} onClick={remember}>{bi(lang,"Merken","Remember")}</button>{editing&&<button className="ghost" onClick={()=>{setEditing(null);setDraft("")}}>{bi(lang,"Abbrechen","Cancel")}</button>}<button className="ghost danger" onClick={async()=>{if(!confirm(bi(lang,"Profil und alle Merksätze löschen? Gespeicherte Gespräche bleiben separat erhalten.","Delete profile and all memories? Saved conversations are kept separately.")))return;try{await api("/coach/profile",{method:"DELETE"});await load()}catch(e){setStatus(String(e))}}}>{bi(lang,"Profil & Gedächtnis löschen","Delete profile & memory")}</button></div></div><p role="status" className="muted">{status}</p></div></details>
}
