"use client";
import {useEffect,useState} from "react";
import {api} from "../lib/api";
import {bi,useI18n} from "../lib/i18n";
import {sourceLabel} from "../lib/sources";
type O=Record<string,any>;
export default function DailyCompanion({compact=false}:{compact?:boolean}){
 const {lang}=useI18n(),de=lang!=="en";const [data,setData]=useState<O|null>(null),[check,setCheck]=useState<O>({}),[status,setStatus]=useState(""),[saving,setSaving]=useState(false),[quality,setQuality]=useState<O|null>(null);
 async function load(){try{const [b,c]=await Promise.all([api<O>("/coach/briefing"),api<O>("/coach/check-in")]);setData(b);setCheck(c)}catch(e){setStatus(String(e))}}
 useEffect(()=>{void load()},[]);
 async function save(){setSaving(true);try{await api("/coach/check-in",{method:"PUT",body:JSON.stringify(check)});await load();setStatus(bi(lang,"Check-in gespeichert – Coach und Planung können ihn berücksichtigen.","Check-in saved — available for coaching and planning."))}catch(e){setStatus(String(e))}finally{setSaving(false)}}
 const reasons:O={hard_feedback:bi(lang,"Eine der letzten Einheiten war laut deinem Feedback zu schwer.","Your feedback marked a recent session as too hard."),low_energy:bi(lang,"Du meldest wenig Energie.","You report low energy."),soreness:bi(lang,"Du meldest starken Muskelkater.","You report strong soreness."),discomfort:bi(lang,"Du hast Beschwerden angegeben. Kläre zunächst, was heute möglich ist.","You reported discomfort. Clarify what is appropriate today first."),no_time:bi(lang,"Heute hast du keine Zeit eingeplant.","You have no time available today."),three_active_days:bi(lang,"An den letzten drei Tagen wurden Aktivitäten erfasst.","Activities were recorded on each of the last three days."),short_sleep:bi(lang,"Für heute wurden weniger als sechs Stunden Schlaf erfasst.","Less than six hours of sleep were recorded for today.")};
 const title=data?.mode==="check_discomfort"?bi(lang,"Heute zählt dein Befinden","Focus on how you feel today"):data?.mode==="easy"?bi(lang,"Heute darf es ruhiger sein","Make room for an easier day"):data?.mode==="review_plan"?bi(lang,"Dein nächster Schritt steht bereit","Your next step is ready"):bi(lang,"Wie geht es dir heute?","How are you feeling today?");
 const ask=de?"Was soll ich heute trainieren? Nutze meine ausgewählten Daten, mein Profil und meinen heutigen Check-in. Antworte kurz mit einer Empfehlung und Begründung.":"What should I train today? Use my selected data, profile and today's check-in. Give a short recommendation and reason.";
 const current=data?.current_week||{},previous=data?.previous_week||{};
 return <section className={`daily-companion ${compact?"compact":""}`}><div className="daily-focus"><div className="daily-focus-top"><span className="eyebrow">✦ {bi(lang,"Dein täglicher Begleiter","Your daily companion")}</span><span className="tag">{bi(lang,"Heute","Today")}</span></div><h2>{title}</h2><p>{data?.reasons?.length?data.reasons.map((r:string)=>reasons[r]).join(" "):bi(lang,"Verbinde deine Messwerte mit deinem Gefühl. Ein kurzer Check-in hilft deinem Coach, den Tag passend zu planen.","Combine your readings with how you feel. A quick check-in helps your coach shape your day.")}</p><div className="daily-stats"><span><strong>{current.sessions??"—"}</strong>{bi(lang,"Einheiten · 7 Tage","sessions · 7 days")}</span><span><strong>{current.minutes??"—"}<small> min</small></strong>{bi(lang,"Erfasste Bewegung","recorded activity")}</span><span><strong>{current.active_days??"—"}<small> / 7</small></strong>{bi(lang,"Aktive Tage","active days")}</span></div>{data?.profile?.goal&&<div className="daily-goal"><small>{bi(lang,"Dein Ziel im Blick","Your goal in focus")}</small><strong>{data.profile.goal}</strong>{data.profile.target_date&&<span>{bi(lang,"Zieldatum","Target date")}: {data.profile.target_date}</span>}</div>}{data?.upcoming?.[0]&&<div className="next-session"><span>↗</span><div><small>{data.upcoming[0].date}</small><strong>{data.upcoming[0].name} · {data.upcoming[0].duration_min} min</strong></div><a href="/training">→</a></div>}<a className="primary-link" href={`/coach?prompt=${encodeURIComponent(ask)}`}>{bi(lang,"Was passt heute zu mir?","What suits me today?")} →</a><details className="briefing-evidence"><summary>{bi(lang,"Warum diese Einschätzung?","Why this suggestion?")}</summary><p className="muted">{bi(lang,"Regelbasierter Tagesimpuls aus erfassten Daten und deinem Check-in. Fehlende Einträge bedeuten weder Erholung noch Inaktivität.","A rule-based daily suggestion using recorded data and your check-in. Missing records prove neither recovery nor inactivity.")}</p>{data?.evidence?.map((e:O)=><div className="evidence-row" key={e.metric}><b>{({sleep:bi(lang,"Schlaf","Sleep"),hrv:"HRV",resting_hr:bi(lang,"Ruhepuls","Resting HR"),hydration:bi(lang,"Trinkmenge","Water intake")} as O)[e.metric]}</b><span>{e.metric==="sleep"?`${(e.value/3600).toFixed(1)} h`:e.metric==="hydration"?`${(e.value/1000).toFixed(1)} l`:`${e.value} ${e.metric==="hrv"?"ms":"bpm"}`}</span><small>{sourceLabel(e.source,lang)} · {e.date}{e.age_days>0?` · ${e.age_days} ${bi(lang,"Tage alt","days old")}`:""}</small></div>)}</details></div>
 <div className="daily-check"><details open={!compact}><summary><span className="eyebrow">{bi(lang,"Ein Moment für dich","A moment for you")}</span><h3>{bi(lang,"Dein Tages-Check-in","Your daily check-in")}</h3></summary><label>{bi(lang,"Energie","Energy")}<div className="feeling-scale">{[1,2,3,4,5].map(n=><button type="button" key={n} aria-pressed={check.energy===n} className={check.energy===n?"active":"ghost"} onClick={()=>setCheck({...check,energy:check.energy===n?null:n})}>{["▁","▂","▃","▄","▅"][n-1]}<small>{n}</small></button>)}</div><small>{bi(lang,"1 erschöpft · 5 voller Energie","1 exhausted · 5 full of energy")}</small></label><div className="checkin-grid"><label>{bi(lang,"Muskelkater","Soreness")}<select value={check.soreness??""} onChange={e=>setCheck({...check,soreness:e.target.value?Number(e.target.value):null})}><option value="">—</option>{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} {n===1?bi(lang,"· keiner","· none"):n===5?bi(lang,"· stark","· strong"):""}</option>)}</select></label><label>{bi(lang,"Zeit heute (min)","Time today (min)")}<input type="number" min={0} max={480} value={check.minutes??""} onChange={e=>setCheck({...check,minutes:e.target.value===""?null:Number(e.target.value)})}/></label></div><label>{bi(lang,"Beschwerden / Hinweise (optional)","Discomfort / notes (optional)")}<input maxLength={500} value={check.discomfort||""} onChange={e=>setCheck({...check,discomfort:e.target.value})}/></label><div className="companion-actions"><button disabled={saving} onClick={save}>{bi(lang,"Check-in speichern","Save check-in")}</button><button className="ghost compact" onClick={async()=>{try{await api("/coach/check-in",{method:"DELETE"});await load();setStatus(bi(lang,"Check-in gelöscht.","Check-in deleted."))}catch(e){setStatus(String(e))}}}>{bi(lang,"Zurücksetzen","Reset")}</button></div></details><p role="status" className="muted">{status}</p></div>
 {!compact&&<details className="companion-week"><summary><span>↗ {bi(lang,"Dein Wochenrückblick","Your weekly reflection")}</span><small>{bi(lang,"Letzte 7 Tage im Vergleich zu den 7 Tagen davor","Last 7 days compared with the preceding 7 days")}</small></summary><div className="week-comparison"><div><span>{bi(lang,"Diese 7 Tage","These 7 days")}</span><strong>{current.minutes??0} min</strong><small>{current.sessions??0} {bi(lang,"Einheiten","sessions")}</small></div><div><span>{bi(lang,"Die 7 Tage davor","Preceding 7 days")}</span><strong>{previous.minutes??0} min</strong><small>{previous.sessions??0} {bi(lang,"Einheiten","sessions")}</small></div></div><p>{bi(lang,"Trainingszeit beschreibt den Umfang, nicht automatisch die Intensität. Für die Einordnung nutzt dein Coach zusätzlich verfügbare Erholungswerte und dein Feedback.","Training time describes volume, not necessarily intensity. Your coach can also use available recovery readings and feedback.")}</p><a className="text-link" href={`/coach?mode=14&prompt=${encodeURIComponent(de?"Erstelle meinen Wochenrückblick: Vergleiche die letzten 7 Tage mit den 7 Tagen davor anhand der vorhandenen Daten. Berücksichtige mein Ziel, Feedback und Erholung. Gib einen konkreten Vorschlag für die nächste Woche, keinen vollständigen Trainingsplan.":"Review my week: compare the last 7 days with the preceding 7 days using available data. Consider my goal, feedback and recovery. Give one concrete suggestion for next week, not a full plan.")}`}>{bi(lang,"Mit Coach einordnen","Reflect with Coach")} →</a><details onToggle={e=>{if(e.currentTarget.open&&!quality)api<O>("/coach/data-quality").then(setQuality).catch(e=>setStatus(String(e)))}}><summary>{bi(lang,"Datenqualität prüfen","Check data quality")}</summary>{quality&&<p>{quality.possible_duplicates.length} {bi(lang,"mögliche doppelte Aktivitäten in 28 Tagen. Es wird nichts automatisch gelöscht.","possible duplicate activities in 28 days. Nothing is automatically deleted.")}</p>}{quality?.possible_duplicates?.map((p:O)=><p key={p.first_id+p.second_id}><a href={`/activities/${p.first_id}`}>{p.name}</a> · <a href={`/activities/${p.second_id}`}>{bi(lang,"Vergleichseintrag","Compare entry")}</a></p>)}</details></details>}</section>
}
