"use client";

import {useEffect,useState} from "react";
import {useParams} from "next/navigation";
import AppShell from "../../../components/AppShell";
import ActivityExplorer from "../../../components/ActivityExplorer";
import AiReport from "../../../components/AiReport";
import {api} from "../../../lib/api";
import {bi,useI18n} from "../../../lib/i18n";

type AnyObj=Record<string,any>;

function n(v:any){const x=Number(v);return Number.isFinite(x)?x:null}
function num(v:any,d=1){const x=n(v);return x==null?"—":x.toFixed(d)}
function int(v:any){const x=n(v);return x==null?"—":Math.round(x).toLocaleString()}
function duration(v:any){const x=n(v);if(x==null)return"—";const s=Math.max(0,Math.round(x)),h=Math.floor(s/3600),m=Math.floor((s%3600)/60),r=s%60;return h?`${h}:${String(m).padStart(2,"0")}:${String(r).padStart(2,"0")}`:`${m}:${String(r).padStart(2,"0")}`}
function pace(v:any){const x=n(v);if(x==null||x<=0)return"—";let sec=Math.round(x),m=Math.floor(sec/60),s=sec%60;if(s===60){m++;s=0}return`${m}:${String(s).padStart(2,"0")} min/km`}
function contextLabel(lang:"de"|"en",days:any){const d=Number(days);return d===0?bi(lang,"Nur Training","Training only"):d===1?bi(lang,"Dieser Tag","This day"):d===3?bi(lang,"3 Tage","3 days"):d===7?bi(lang,"7 Tage","7 days"):`${d}d`}
function Metric({label,value,note}:{label:string;value:string;note?:string}){return <div className="detail-metric"><div className="metric-label">{label}</div><div className="detail-metric-value">{value}</div>{note&&<div className="kpi-note">{note}</div>}</div>}
function Coverage({label,value}:{label:string;value:any}){const v=Math.max(0,Math.min(100,n(value)??0));return <div className="coverage-row"><span>{label}</span><div className="coverage-track"><i style={{width:`${v}%`}}/></div><strong>{v.toFixed(1)}%</strong></div>}
function pick(x:AnyObj,...keys:string[]){for(const k of keys){if(x?.[k]!=null)return x[k]}return null}
const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));

export default function Detail(){
  const{lang}=useI18n();const de=lang!=="en";const params=useParams<{id:string}>();
  const[d,setD]=useState<AnyObj|null>(null),[series,setSeries]=useState<AnyObj[]>([]),[analysis,setAnalysis]=useState<AnyObj|null>(null),[msg,setMsg]=useState(""),[loading,setLoading]=useState(true);
  const[caps,setCaps]=useState<AnyObj|null>(null),[aiOpen,setAiOpen]=useState(false),[aiPrompt,setAiPrompt]=useState(""),[aiLookback,setAiLookback]=useState(7),[aiModel,setAiModel]=useState(""),[aiTokens,setAiTokens]=useState(3500),[aiCtx,setAiCtx]=useState(8192),[aiBusy,setAiBusy]=useState(false),[aiStatus,setAiStatus]=useState(""),[aiResult,setAiResult]=useState<AnyObj|null>(null),[aiHistory,setAiHistory]=useState<AnyObj[]>([]);
  const jobKey=`pengucoach_activity_ai_job_${params.id}`;
  const load=async()=>{setLoading(true);try{const[detail,ser,ana,cap,hist]=await Promise.all([api<AnyObj>(`/activities/${params.id}`),api<AnyObj>(`/activities/${params.id}/series?limit=5000`),api<AnyObj>(`/activities/${params.id}/analysis`),api<AnyObj>(`/coach/capabilities?locale=${lang}`).catch(()=>null),api<AnyObj[]>(`/coach/activity-analysis/${params.id}`).catch(()=>[])]);setD(detail);setSeries(ser.data??[]);setAnalysis(ana);setCaps(cap);setAiHistory(hist??[]);if(cap?.tasks?.activity_analysis){const t=cap.tasks.activity_analysis;setAiPrompt(t.default_prompt??"");setAiModel(v=>v||t.default_model_id||"");setAiTokens(t.max_output_tokens??3500);setAiCtx(t.context_window_tokens??8192)}if(hist?.length)setAiResult(hist[0])}finally{setLoading(false)}};
  useEffect(()=>{void load();const j=localStorage.getItem(jobKey);if(j){setAiBusy(true);setAiOpen(true);void pollAi(j)}},[params.id,lang]);
  async function analyze(){setMsg(de?"FIT-Analyse wird gestartet…":"Queueing FIT analysis…");try{const r=await api<AnyObj>(`/activities/${params.id}/fit/analyze`,{method:"POST"});setMsg(`${bi(lang,"Analyse gestartet","Analysis queued")}: ${r.task_id}`)}catch(e){setMsg(String(e))}}
  async function pollAi(jobId:string){setAiStatus(de?"Analyse läuft im Hintergrund…":"Analysis is running in the background…");for(let i=0;i<800;i++){try{const j=await api<AnyObj>(`/jobs/${jobId}`);if(j.ready){localStorage.removeItem(jobKey);setAiBusy(false);if(j.successful&&j.result){setAiResult(j.result);setAiHistory(v=>[j.result,...v].slice(0,8));setAiStatus(de?"Analyse abgeschlossen":"Analysis complete");return}setAiStatus(j.error||bi(lang,"Analyse fehlgeschlagen","Analysis failed"));return}setAiStatus(j.progress?.message||bi(lang,"Analyse läuft im Hintergrund…","Analysis is running in the background…"))}catch{}await sleep(1500)}setAiBusy(false);setAiStatus(bi(lang,"Analyse läuft weiter. Seite kann neu geladen werden.","Analysis continues. You can reload the page."))}
  async function runAi(){if(aiBusy||!aiModel)return;setAiBusy(true);setAiStatus(de?"Analyse wird vorbereitet…":"Preparing analysis…");setMsg("");try{const r=await api<AnyObj>("/coach/activity-analysis/jobs",{method:"POST",body:JSON.stringify({activity_id:params.id,lookback_days:aiLookback,prompt:aiPrompt||null,model_id:aiModel,max_tokens:aiTokens,context_window_tokens:aiCtx,locale:lang})});localStorage.setItem(jobKey,r.task_id);void pollAi(r.task_id)}catch(e){setAiBusy(false);setAiStatus(e instanceof Error?e.message:String(e))}}
  if(loading&&!d)return <AppShell><div className="card">{de?"Aktivität wird geladen…":"Loading activity…"}</div></AppShell>;
  if(!d)return <AppShell><div className="card">{de?"Aktivität nicht gefunden.":"Activity not found."}</div></AppShell>;
  const manual=d.source==="manual_upload";const s=analysis?.stats??{};const hr=s.heart_rate??{},sp=s.speed_kmh??{},pw=s.power_w??{},ca=s.cadence??{},el=s.elevation??{},temp=s.temperature_c??{},cov=s.coverage??{};const splits=analysis?.splits??[];const family=s.sport_family??"other";const gx=d.garmin_extra??{};const session=d.metrics?.details?.session??{};const fitLaps=session._laps??[];const fitSets=session._sets??[];const fitLengths=session._lengths??[];
  const avgSpeed=n(d.avg_speed)!=null?n(d.avg_speed)!*3.6:n(sp.avg);const maxSpeed=n(gx.max_speed_mps)!=null?n(gx.max_speed_mps)!*3.6:n(sp.max);
  const aiTask=caps?.tasks?.activity_analysis??{};const models=caps?.eligible_models??[];const selectedModel=models.find((x:AnyObj)=>x.id===aiModel);const meta=aiResult?.metadata??aiResult??{};const usage=aiResult?.usage??meta.usage??{};const wasTruncated=Boolean(aiResult?.truncated??meta.truncated);const outputAdjusted=Boolean(aiResult?.output_budget_adjusted??meta.output_budget_adjusted);const requestedOut=aiResult?.requested_max_output_tokens??meta.requested_max_output_tokens;const resultCtx=aiResult?.context_window_tokens??meta.context_window_tokens;const resultLookback=aiResult?.lookback_days??aiLookback;
  return <AppShell><div className="activity-detail stack">
    <div className="activity-hero between"><div><a className="muted" href="/activities">← {bi(lang,"Aktivitäten","Activities")}</a><h1>{d.name??d.sport_type}</h1><p className="muted">{d.started_at?new Date(d.started_at).toLocaleString(lang==="en"?"en-GB":"de-DE"):""} · {d.sport_type}{manual?` · ${bi(lang,"manuell importiert","manual import")}`:""}</p></div><div className="row"><span className={`fit-pill ${d.fit_status}`}>{d.fit_status}</span><button className="ai-button" onClick={()=>setAiOpen(v=>!v)}>✦ {bi(lang,"AI Analyse","AI analysis")}{aiTask.default_model?` · ${aiTask.default_model}`:""}</button>{!manual&&<button className="ghost" onClick={analyze}>{bi(lang,"FIT neu analysieren","Re-analyze FIT")}</button>}</div></div>
    {msg&&<div className="card subtle">{msg}</div>}
    {aiOpen&&<section className="card ai-analysis-modern"><div className="ai-analysis-head"><div><span className="eyebrow">AI DEEP ANALYSIS</span><h2>{bi(lang,"Trainings-Tiefenanalyse","Training deep analysis")}</h2><p className="muted">{manual?bi(lang,"Importierte Trainingsdaten + PenguCoach-Analytics + Tages-, 3-Tage- oder 7-Tage-Kontext. Die Analyse läuft als Hintergrundjob weiter, auch wenn du die Seite neu lädst.","Imported activity data + PenguCoach analytics + day, 3-day or 7-day context. Analysis continues as a background job even if you reload the page."):bi(lang,"Garmin-Fakten + FIT-Analytics + Tages-, 3-Tage- oder 7-Tage-Kontext. Die Analyse läuft als Hintergrundjob weiter, auch wenn du die Seite neu lädst.","Garmin facts + FIT analytics + day, 3-day or 7-day context. Analysis continues as a background job even if you reload the page.")}</p></div><div className="coach-model-chip"><span className={`ai-local-dot ${selectedModel?.local?"local":"cloud"}`}/><div><small>{bi(lang,"Modell","Model")}</small><strong>{selectedModel?.display_name??aiTask.default_model??"—"}</strong><span>{selectedModel?.provider??aiTask.default_provider??""}</span></div></div></div>
      <div className="ai-analysis-settings"><label>{bi(lang,"Modell","Model")}<select value={aiModel} onChange={e=>setAiModel(e.target.value)}>{models.map((x:AnyObj)=><option key={x.id} value={x.id}>{x.display_name} · {x.provider} · {x.local?"LOCAL":"CLOUD"}</option>)}</select></label><label>{bi(lang,"Analyse-Kontext","Analysis context")}<select value={aiLookback} onChange={e=>setAiLookback(Number(e.target.value))}><option value={0}>{bi(lang,"Nur dieses Training","This training only")}</option><option value={1}>{bi(lang,"Dieser Tag","This day")}</option><option value={3}>{bi(lang,"3 Tage","3 days")}</option><option value={7}>{bi(lang,"7 Tage + 3-Tage-Vergleich","7 days + 3-day comparison")}</option></select></label><label>{bi(lang,"Kontextfenster","Context window")}<div className="ai-number-control"><input type="number" min={2048} max={aiTask.context_window_tokens??262144} step={1024} value={aiCtx} onChange={e=>setAiCtx(Math.min(aiTask.context_window_tokens??262144,Number(e.target.value)))}/><span>tokens</span></div></label><label>{bi(lang,"Max. Antwort","Max response")}<div className="ai-number-control"><input type="number" min={128} max={aiTask.max_output_tokens??8192} step={1} value={aiTokens} onChange={e=>setAiTokens(Math.min(aiTask.max_output_tokens??8192,Number(e.target.value)))}/><span>tokens</span></div></label></div>
      <div className="ai-analysis-foot"><details><summary>{bi(lang,"Prompt anzeigen / anpassen","Show / edit prompt")}</summary><textarea className="prompt-editor modern" value={aiPrompt} onChange={e=>setAiPrompt(e.target.value)}/></details><div className="ai-run-actions">{aiStatus&&<span className={`ai-job-status ${aiBusy?"running":""}`}>{aiBusy&&<i/>}{aiStatus}</span>}<button disabled={aiBusy||!aiModel} onClick={runAi}>{aiBusy?bi(lang,"Analyse läuft…","Analysis running…"):bi(lang,"AI Analyse starten","Start AI analysis")}</button></div></div>
    </section>}
    {aiResult&&<section className="card ai-result-modern"><div className="ai-result-head"><div><span className="eyebrow">AI ANALYSIS</span><h2>{bi(lang,"Letzte AI-Auswertung","Latest AI analysis")}</h2></div><div className="ai-run-meta-modern"><strong>{aiResult.model??aiResult.model_name}</strong><div><span>{aiResult.provider??aiResult.provider_name}</span><span>{contextLabel(lang,resultLookback)}</span><span>ctx {resultCtx??"—"}</span><span>{aiResult.max_output_tokens??"—"} out</span></div></div></div>{outputAdjusted&&<div className="ai-budget-adjusted">ⓘ {bi(lang,`PenguCoach hat das effektive Antwortbudget von ${requestedOut??"?"} auf ${aiResult.max_output_tokens??"?"} Tokens reduziert, damit die Aktivitätsdaten in das gewählte Kontextfenster passen. Für längere Antworten das Kontextfenster erhöhen.`,`PenguCoach reduced the effective response budget from ${requestedOut??"?"} to ${aiResult.max_output_tokens??"?"} tokens so the activity data fits in the selected context window. Increase the context window for longer responses.`)}</div>}{wasTruncated&&<div className="ai-truncated-warning">⚠ <strong>{bi(lang,"Antwortlimit erreicht.","Response limit reached.")}</strong> {bi(lang,"Die Analyse wurde abgeschnitten. Erhöhe „Max. Antwort“ oder das Kontextfenster und starte sie erneut.","The analysis was truncated. Increase “Max response” or the context window and run it again.")}</div>}<div className="ai-content modern"><AiReport content={aiResult.content}/></div><div className="ai-result-stats"><span>{usage.input_tokens??"?"} {bi(lang,"Input-Tokens","input tokens")}</span><span>{usage.output_tokens??"?"} {bi(lang,"Output-Tokens","output tokens")}</span><span>{meta.context_estimated_tokens??aiResult.context_estimated_tokens??"?"} {bi(lang,"Kontext geschätzt","context estimated")}</span><span>{meta.stop_reason??aiResult.stop_reason??"stop"}</span></div>{aiHistory.length>1&&<div className="ai-history-strip"><strong>{bi(lang,"Frühere Analysen","Previous analyses")}</strong>{aiHistory.slice(0,5).map((x:AnyObj,i:number)=><button type="button" className="ghost compact" key={x.id??x.run_id??i} onClick={()=>setAiResult(x)}>{x.created_at?new Date(x.created_at).toLocaleString(de?"de-DE":"en-GB"):`#${i+1}`} · {x.model??x.model_name}</button>)}</div>}</section>}

    <section className="metric-board">
      <Metric label={bi(lang,"Distanz","Distance")} value={n(d.distance_m)!=null?`${num(n(d.distance_m)!/1000,2)} km`:"—"}/>
      <Metric label={bi(lang,"Dauer","Duration")} value={duration(d.duration_seconds)}/>
      <Metric label={bi(lang,"Bewegungszeit","Moving time")} value={duration(d.moving_seconds)}/>
      <Metric label={bi(lang,"Kalorien","Calories")} value={n(d.calories)!=null?`${int(d.calories)} kcal`:"—"}/>
      <Metric label={bi(lang,"Trainingslast","Training load")} value={n(d.training_load)!=null?int(d.training_load):"—"} note={!manual?"Garmin Activity Training Load":undefined}/>
      <Metric label={bi(lang,"Aerober Effekt","Aerobic effect")} value={n(d.aerobic_training_effect)!=null?num(d.aerobic_training_effect,1):"—"}/>
    </section>

    <section className="detail-grid-4">
      <div className="card stat-group"><h2>♥ {bi(lang,"Herzfrequenz","Heart rate")}</h2><div className="mini-metrics"><Metric label={bi(lang,"Minimum","Minimum")} value={n(gx.min_hr_bpm??hr.min)!=null?`${int(gx.min_hr_bpm??hr.min)} bpm`:"—"}/><Metric label={bi(lang,"Schnitt","Average")} value={`${int(d.avg_hr??hr.avg)}${n(d.avg_hr??hr.avg)!=null?" bpm":""}`}/><Metric label={bi(lang,"Maximum","Maximum")} value={`${int(d.max_hr??hr.max)}${n(d.max_hr??hr.max)!=null?" bpm":""}`}/></div></div>
      <div className="card stat-group"><h2>↗ {bi(lang,"Geschwindigkeit / Pace","Speed / pace")}</h2><div className="mini-metrics"><Metric label={bi(lang,"Ø Geschwindigkeit","Avg speed")} value={avgSpeed!=null?`${num(avgSpeed,1)} km/h`:"—"}/><Metric label={bi(lang,"Max Geschwindigkeit","Max speed")} value={maxSpeed!=null?`${num(maxSpeed,1)} km/h`:"—"}/><Metric label={bi(lang,"Ø Pace","Avg pace")} value={pace(s.pace_s_per_km?.avg)}/></div></div>
      <div className="card stat-group"><h2>⌁ {bi(lang,"Höhenprofil","Elevation")}</h2><div className="mini-metrics"><Metric label={bi(lang,"Hoch","Ascent")} value={n(d.elevation_gain??gx.elevation_gain_m??el.gain_m)!=null?`${int(d.elevation_gain??gx.elevation_gain_m??el.gain_m)} m`:"—"}/><Metric label={bi(lang,"Runter","Descent")} value={n(gx.elevation_loss_m??el.loss_m)!=null?`${int(gx.elevation_loss_m??el.loss_m)} m`:"—"}/><Metric label={bi(lang,"Min / Max Höhe","Min / max elevation")} value={n(gx.min_elevation_m??el.min_m)!=null||n(gx.max_elevation_m??el.max_m)!=null?`${num(gx.min_elevation_m??el.min_m,0)} / ${num(gx.max_elevation_m??el.max_m,0)} m`:"—"}/><Metric label={bi(lang,"Steilste Steigung","Steepest climb")} value={n(el.steepest_climb_pct)!=null?`${num(el.steepest_climb_pct,1)} %`:"—"}/></div></div>
      <div className="card stat-group"><h2>⚡ {bi(lang,"Leistung & Kadenz","Power & cadence")}</h2><div className="mini-metrics"><Metric label={bi(lang,"Ø Leistung","Avg power")} value={n(d.avg_power??pw.avg)!=null?`${int(d.avg_power??pw.avg)} W`:"—"}/><Metric label={bi(lang,"Max Leistung","Max power")} value={n(gx.max_power_w??pw.max)!=null?`${int(gx.max_power_w??pw.max)} W`:"—"}/><Metric label="Normalized Power" value={n(gx.normalized_power_w??pw.normalized)!=null?`${int(gx.normalized_power_w??pw.normalized)} W`:"—"}/><Metric label={bi(lang,"Ø / Max Kadenz","Avg / max cadence")} value={n(d.avg_cadence??ca.avg)!=null||n(gx.max_cadence??ca.max)!=null?`${int(d.avg_cadence??ca.avg)} / ${int(gx.max_cadence??ca.max)} rpm`:"—"}/></div></div>
    </section>

    <section className="card chart-card"><div className="between"><div><h2>{bi(lang,"Interaktive Aktivitätsanalyse","Interactive activity analysis")}</h2><p className="muted">{bi(lang,"Herzfrequenz, Geschwindigkeit, Höhe, Leistung, Kadenz und Steigung überlagern oder synchron untereinander anzeigen.","Overlay heart rate, speed, elevation, power, cadence and grade, or show them as synchronized panels.")}</p></div><span className="badge">{series.length.toLocaleString()} {bi(lang,"Datenpunkte","samples")}</span></div><ActivityExplorer data={series} lang={lang}/></section>

    {splits.length>0&&<section className="card"><div className="between"><div><h2>{family==="swim"?bi(lang,"100-m-Splits","100 m splits"):bi(lang,"Kilometer-Splits","Kilometre splits")}</h2><p className="muted">{bi(lang,"Pace, Herzfrequenz, Leistung, Kadenz und Höhenmeter pro Abschnitt.","Pace, heart rate, power, cadence and elevation for each split.")}</p></div><span className="badge">{splits.length} splits</span></div><div className="table-scroll"><table className="splits-table"><thead><tr><th>#</th><th>{bi(lang,"Zeit","Time")}</th><th>Pace</th><th>{bi(lang,"Geschw.","Speed")}</th><th>Ø HR</th><th>Max HR</th><th>Ø W</th><th>Max W</th><th>{bi(lang,"Kadenz","Cadence")}</th><th>↗</th><th>↘</th><th>{bi(lang,"Steigung","Grade")}</th></tr></thead><tbody>{splits.map((x:AnyObj)=><tr key={x.index}><td><strong>{x.label}</strong></td><td>{duration(x.elapsed_s)}</td><td>{pace(x.pace_s_per_km)}</td><td>{n(x.avg_speed_kmh)!=null?`${num(x.avg_speed_kmh,1)} km/h`:"—"}</td><td>{int(x.avg_hr)}</td><td>{int(x.max_hr)}</td><td>{int(x.avg_power)}</td><td>{int(x.max_power)}</td><td>{int(x.avg_cadence)}</td><td>{n(x.ascent_m)!=null?`${int(x.ascent_m)} m`:"—"}</td><td>{n(x.descent_m)!=null?`${int(x.descent_m)} m`:"—"}</td><td>{n(x.avg_grade_pct)!=null?`${num(x.avg_grade_pct,1)} %`:"—"}</td></tr>)}</tbody></table></div></section>}

    {fitLaps.length>0&&<section className="card"><div className="between"><div><h2>{bi(lang,"Runden / Intervalle","Laps / intervals")}</h2><p className="muted">{bi(lang,"Vom Gerät gespeicherte Runden, Intervalle oder Auto-Laps.","Device-recorded laps, intervals or auto laps.")}</p></div><span className="badge">{fitLaps.length}</span></div><div className="table-scroll"><table className="splits-table"><thead><tr><th>#</th><th>{bi(lang,"Distanz","Distance")}</th><th>{bi(lang,"Zeit","Time")}</th><th>Ø HR</th><th>Max HR</th><th>{bi(lang,"Geschw.","Speed")}</th><th>Ø W</th><th>↗</th></tr></thead><tbody>{fitLaps.map((x:AnyObj,i:number)=><tr key={i}><td><strong>{i+1}</strong></td><td>{n(pick(x,"total_distance"))!=null?`${num(n(pick(x,"total_distance"))!/1000,2)} km`:"—"}</td><td>{duration(pick(x,"total_elapsed_time","total_timer_time"))}</td><td>{int(pick(x,"avg_heart_rate"))}</td><td>{int(pick(x,"max_heart_rate"))}</td><td>{n(pick(x,"enhanced_avg_speed","avg_speed"))!=null?`${num(n(pick(x,"enhanced_avg_speed","avg_speed"))!*3.6,1)} km/h`:"—"}</td><td>{int(pick(x,"avg_power"))}</td><td>{n(pick(x,"total_ascent"))!=null?`${int(pick(x,"total_ascent"))} m`:"—"}</td></tr>)}</tbody></table></div></section>}

    {fitSets.length>0&&<section className="card"><div className="between"><div><h2>{bi(lang,"Krafttraining · Sätze","Strength · sets")}</h2><p className="muted">{bi(lang,"Sätze und Wiederholungen aus dem FIT-Workout, sofern vom Gerät gespeichert.","Sets and repetitions from the FIT workout when recorded by the device.")}</p></div><span className="badge">{fitSets.length}</span></div><div className="table-scroll"><table className="splits-table"><thead><tr><th>#</th><th>{bi(lang,"Typ","Type")}</th><th>{bi(lang,"Wiederholungen","Reps")}</th><th>{bi(lang,"Gewicht","Weight")}</th><th>{bi(lang,"Dauer","Duration")}</th><th>{bi(lang,"Kategorie","Category")}</th></tr></thead><tbody>{fitSets.map((x:AnyObj,i:number)=><tr key={i}><td><strong>{i+1}</strong></td><td>{String(pick(x,"set_type")??"—")}</td><td>{int(pick(x,"repetitions"))}</td><td>{n(pick(x,"weight"))!=null?`${num(pick(x,"weight"),1)} kg`:"—"}</td><td>{duration(pick(x,"duration"))}</td><td>{String(pick(x,"category","category_subtype")??"—")}</td></tr>)}</tbody></table></div></section>}

    {fitLengths.length>0&&family==="swim"&&<section className="card"><div className="between"><div><h2>{bi(lang,"Schwimmen · Bahnen","Swimming · lengths")}</h2><p className="muted">{bi(lang,"Bahnen, Schwimmstil, Züge und Zeit aus dem FIT-File.","Pool lengths, stroke type, strokes and time from the FIT file.")}</p></div><span className="badge">{fitLengths.length}</span></div><div className="table-scroll"><table className="splits-table"><thead><tr><th>#</th><th>{bi(lang,"Zeit","Time")}</th><th>{bi(lang,"Stil","Stroke")}</th><th>{bi(lang,"Züge","Strokes")}</th><th>{bi(lang,"Geschw.","Speed")}</th><th>{bi(lang,"Typ","Type")}</th></tr></thead><tbody>{fitLengths.map((x:AnyObj,i:number)=><tr key={i}><td><strong>{i+1}</strong></td><td>{duration(pick(x,"total_elapsed_time","total_timer_time"))}</td><td>{String(pick(x,"swim_stroke")??"—")}</td><td>{int(pick(x,"total_strokes"))}</td><td>{n(pick(x,"avg_speed"))!=null?`${num(n(pick(x,"avg_speed"))!*3.6,1)} km/h`:"—"}</td><td>{String(pick(x,"length_type")??"—")}</td></tr>)}</tbody></table></div></section>}

    <section className="detail-grid-2">
      <div className="card"><h2>PenguCoach Analytics</h2>{d.metrics?<div className="analytics-grid"><Metric label="HR drift" value={n(d.metrics.hr_drift)!=null?`${num(d.metrics.hr_drift,1)} %`:"—"}/><Metric label="Power drift" value={n(d.metrics.power_drift)!=null?`${num(d.metrics.power_drift,1)} %`:"—"}/><Metric label="Aerobic decoupling" value={n(d.metrics.aerobic_decoupling)!=null?`${num(d.metrics.aerobic_decoupling,1)} %`:"—"}/><Metric label="Pace consistency" value={n(d.metrics.pace_consistency)!=null?`${num(d.metrics.pace_consistency,1)} / 100`:"—"}/><Metric label="Cadence drift" value={n(d.metrics.cadence_drift)!=null?`${num(d.metrics.cadence_drift,1)} %`:"—"}/><Metric label={bi(lang,"Datenqualität","Data quality")} value={n(d.metrics.data_quality_score)!=null?`${num(d.metrics.data_quality_score,1)} %`:"—"}/></div>:<p className="muted">{bi(lang,"Noch keine FIT-Analyse vorhanden.","No FIT analysis available yet.")}</p>}</div>
      <div className="card"><h2>{bi(lang,"Datenabdeckung","Data coverage")}</h2><Coverage label={bi(lang,"Herzfrequenz","Heart rate")} value={cov.heart_rate}/><Coverage label={bi(lang,"Geschwindigkeit","Speed")} value={cov.speed}/><Coverage label={bi(lang,"Leistung","Power")} value={cov.power}/><Coverage label={bi(lang,"Kadenz","Cadence")} value={cov.cadence}/><Coverage label={bi(lang,"Höhe","Elevation")} value={cov.altitude}/><Coverage label="GPS" value={cov.gps}/></div>
    </section>

    {(Object.keys(gx).length>0||n(temp.avg)!=null)&&<section className="card"><h2>{bi(lang,"Weitere Sportmetriken","Additional sport metrics")}</h2><div className="extra-metrics">{n(temp.avg)!=null&&<Metric label={bi(lang,"Temperatur Ø / Min / Max","Temperature avg / min / max")} value={`${num(temp.avg,1)} / ${num(temp.min,1)} / ${num(temp.max,1)} °C`}/>} {n(gx.avg_stride_length_cm)!=null&&<Metric label={bi(lang,"Schrittlänge","Stride length")} value={`${num(gx.avg_stride_length_cm,1)} cm`}/>} {n(gx.avg_vertical_oscillation_cm)!=null&&<Metric label={bi(lang,"Vertikale Bewegung","Vertical oscillation")} value={`${num(gx.avg_vertical_oscillation_cm,1)} cm`}/>} {n(gx.avg_ground_contact_time_ms)!=null&&<Metric label={bi(lang,"Bodenkontaktzeit","Ground contact time")} value={`${num(gx.avg_ground_contact_time_ms,0)} ms`}/>} {n(gx.avg_swolf)!=null&&<Metric label="SWOLF" value={num(gx.avg_swolf,1)}/>} {n(gx.pool_length_m)!=null&&<Metric label={bi(lang,"Beckenlänge","Pool length")} value={`${num(gx.pool_length_m,0)} m`}/>}</div></section>}

    <section className="card notice"><h2>{bi(lang,"Quelle & Interpretation","Source & interpretation")}</h2><p className="muted">{manual?bi(lang,"Diese Aktivität wurde manuell aus einer Trainingsdatei importiert. PenguCoach übernimmt verfügbare Dateiwerte und berechnet Zeitreihen, Splits, Steigung sowie deterministische Trainingsmetriken lokal. Fehlende Sensorwerte bleiben fehlend und werden nicht erfunden.","This activity was imported manually from an activity file. PenguCoach uses the values available in the file and calculates time series, splits, grade and deterministic training metrics locally. Missing sensor values remain missing and are never invented."):bi(lang,"Garmin-Gesamtwerte sind die primäre Quelle für Distanz, Zeit, Herzfrequenz, Leistung, Kadenz und Höhenmeter, sofern Garmin sie liefert. Original-FIT bleibt die Quelle für Zeitreihen. PenguCoach berechnet Diagramme, Splits, Steigung und deterministische Trainingsmetriken lokal. Fehlende Sensorwerte werden als fehlend angezeigt und nicht als 0 oder als erfundene Schätzung ersetzt.","Garmin summary values are the primary source for distance, time, heart rate, power, cadence and elevation totals when available. The original FIT remains the source for time series. PenguCoach calculates charts, splits, grade and deterministic training metrics locally. Missing sensor data is shown as missing rather than zero or an invented estimate.")}</p></section>
  </div></AppShell>
}
